### ISSUE TITLE
info su accesso tramite LAN

### ISSUE THREAD

**Issue by anxdroid** [andrea-mattioli/mattiols_hassio_repository#1]
ciao,
ho appena richiesto l'api key a legrand per testare il componente e appena possibile spero di dare un contributo nello sviluppo. Sarei interessato, soprattutto, a trovare un modo per accedere al device direttamente, tramite porta TCP, anche se sembra chiuso a riccio. nmap non trova nulla di aperto (i device tuya hanno almeno la porta IRC aperta)...

**Comment by andrea-mattioli** [comment]
Non puoi contattare direttamente il device a meno che tu non voglia riscriverti il firmware!
