### ISSUE TITLE
Update 2.2

### ISSUE THREAD

**Issue by yashijoe** [andrea-mattioli/mattiols_hassio_repository#13]
Hello Andrea, since last update I get following message, thanks.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:25:21] INFO: Setup config file...
[10:25:21] INFO: Starting Python Api...
[10:25:21] INFO: Starting MQTT Client...
  File "bticino.py", line 446
    "EndPointUrl":   ,
                     ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "mqtt.py", line 5, in <module>
    from bticino import send_thermostat_cmd, load_api_config_arg
  File "/hassio_bticino_smarter/bticino.py", line 446
    "EndPointUrl":   ,
                     ^
SyntaxError: invalid syntax
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by andrea-mattioli** [comment]
Hi click reload from supervisor and rebuild the addon
thanks

**Comment by yashijoe** [comment]
yes, it works, thank you!
