### ISSUE TITLE
HASSOS date wrong and BOOST incorrect

### ISSUE THREAD

**Issue by SmartM-ui** [andrea-mattioli/mattiols_hassio_repository#14]
Hi @andrea-mattioli ,
unfortunately with my configuration (RPI4 + HASSOS) the thermostat boost is not managed correctly and overlaps the thermostat settings making the Home Assistant commands prevail!

Example:
If I start the 30-minute boost from the thermostat, on MQTT explorer, the data of 1h 30m is reported and the thermostat setting is often overwritten
If I start the 30-minute boost from the card in Home Assistant, the boost is not set on the thermostat and MQTT explorer reports the status "false"

Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:467
Integration: MQTT (documentation, issues)
Invalid modes mode: false 

Logger: homeassistant.helpers.template
Source: helpers/template.py:453
    Error parsing value: 'bool object' has no attribute 'setpoint' (value: false, template: {{ value_json.setpoint|round (1) }})
    Error parsing value: 'bool object' has no attribute 'mode' (value: false, template: {% if value_json.mode.upper() == "OFF" %} off {% elif value_json.mode.upper() == "PROTECTION" %} off {% elif value_json.function.upper() == "HEATING" %} heat {% elif value_json.function.upper() == "COOLING" %} cool {% elif value_json.mode.upper() == "AUTOMATIC" %} on {% elif value_json.mode.upper() == "MANUAL" %} on {% endif %} )

Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:413
Integration: MQTT (documentation, issues)
    Could not parse temperature from
    Could not parse temperature from false

From the Home Assistant card only the 90-minute boost works, even if it reports the remaining time of 2h 30m

I also report the addon data after HOST RPI4 Startup 9.36 am
I also inform you that all my addons (ADB, MariaDB, ZigBee2Mqtt, Mosquitto, DusckDNS, Nginx, etc.) have the correct date and time. **Only the SSH addon and your Bticino and Reverse Proxy addons report the time back one hour**

ADDON BTICINO **(time -1 hour)**
[services.d] starting services
[08:37:05] INFO: Setup config file...
... ...
 * Running on http://0.0.0.0:5588/ (Press CTRL+C to quit)
xxx.xxx.xxx.xxx - - [02/Nov/2020 08:39:59] "GET /info HTTP/1.1" 200 -

ADDON MOSQUITTO **(correct time)**
[09:36:48] INFO: Setup mosquitto configuration
... ...
1604306231: New connection from 172.30.32.1 on port 1883.
1604306231: New client connected from 172.30.32.1 as Bticino_X8000 (p2, c1, k60, u'MQTT').
1604306253: New connection from 172.30.32.1 on port 1883.
[INFO] found homeassistant on local database
1604306253: New client connected from 172.30.32.1 as auto-Axxx5 (p2, c1, k60, u'homeassistant').

MQTT EXPLORER **(correct time)**
QoS: 0 02/11/2020 09:50:03
{"name": "Thermostat", "mode": "AUTOMATIC", "function": "HEATING", "state": "INACTIVE", "setpoint": "7.00000", "temperature": "19.3", "humidity": "73.4"}

I also verified that the same time problem is present in your other "Reverse Proxy" addon, while duckdns and nginx report the correct time:

ADDON REVERSE PROXY **(time -1 hour)**
... ...
[08:37:06] INFO: start conf for xxx.duckdns.org

Test by stopping your Reverse proxy addon
ADDON DUCKDNS **(correct time)**
...
+ Account already registered!
[09:46:35] INFO: OK

ADDON NGINX **(correct time)**
...
[09:47:14] INFO: Running nginx...

As other information, I can report that HASSOS with the commands:
**now () and sensor.time report the correct time**
utcnow () and sensor.time_utc turn the time back one hour

Is it possible to set your addons / logs with the time zone of Europe / Italy?

Thank you for your work and for giving the possibility to integrate Bticino in Home Assistant

**Comment by andrea-mattioli** [comment]
Check your HA machine date:
open terminal from ssh and write "date", my addon's use machine date

A.

**Comment by SmartM-ui** [comment]
> Check your HA machine date:
> open terminal from ssh and write "date", my addon's use machine date
> 
> A.

Hi Andrea,
Thanks for the reply.
I have seen you use the "date" command.
I was wondering if it was possible, instead, to use the Home Assistant sensor.time which turns out to be right and as it is normally used in most addons (I have no "timer" problems or time-out with other addons or automations), even if the value reported by the terminal date is set in UTC.
Anyway thanks again for the development of this project.
I am starting from scratch with a fresh installation of HASSOS to try to report the CET value in my Raspberry.
Thanks again
