### ISSUE TITLE
subscription_key

### ISSUE THREAD

**Issue by maxambro** [andrea-mattioli/mattiols_hassio_repository#15]
where I can find the key?

**Comment by andrea-mattioli** [comment]
read the documentation it says ...


## 1. First step

### 1.1. Register a Developer account
Sign up for a new Developer account on Works with Legrand website (https://developer.legrand.com/login).

### 1.2. Subscribe to Legrand APIs
Sign in, go to menu "API > Subscriptions" and make sure you have "Starter Kit for Legrand APIs" subscription activated; if not, activate it.

![Alt text](https://github.com/andrea-mattioli/bticino_X8000_rest_api/raw/test/screenshots/subscription.PNG?raw=true "App Register")

**Comment by maxambro** [comment]
Thanks but Subscription Key is the same as Subscription name?
Best regards
Massimo

Il giorno lun 9 nov 2020 alle ore 08:30 andrea-mattioli <
notifications@github.com> ha scritto:

**Comment by andrea-mattioli** [comment]
Subscription key it's "primary key"

**Comment by maxambro** [comment]
Perfetto! Grazie.
Continuo ad avere problemi...Sotto il log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:15:02] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a
production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5588/ (Press CTRL+C to quit)
151.91.37.84 - - [09/Nov/2020 10:15:44] code 400, message Bad request
version ('\x8f+"\x04')
151.91.37.84 - - [09/Nov/2020 10:15:44] "      ü   õŠjï £Ôû ¦  b”Kd’[
¨—nelIˆdr!N 5±"gÜôÙ»MÖ @ôYû£(Sd  +" 	" HTTPStatus.BAD_REQUEST -

Il mio file Config è questo...

client_id: xxxxxxxxxxxxxxxxxxxxxxxxxxx
client_secret: xxxxxxxxxxxxxxxxxxxxxxx
subscription_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
domain: maxambro.duckdns.org
haip: 192.168.1.4
mqtt_broker: 172.30.32.1
mqtt_port: 1883
mqtt_user: mqtt_user
mqtt_pass: Gabriele03


Ho il dubbio per mqtt_Broker e port...non so dove trovarli...ho messo
quello che trovo sul log di Mosquitto broker...

Grazie ancora sulla disponibilità

Massimo




Il giorno lun 9 nov 2020 alle ore 11:12 andrea-mattioli <
notifications@github.com> ha scritto:

**Comment by andrea-mattioli** [comment]
Quale versione dell'Addon stai usando v2?
HAIP è l'indirizzo interno del tuo home Assistant 192.168.1.X
per l'mqtt devi usare sempre l'ip di HA se usi mosquitto ad esempio che gira come container.

**Comment by maxambro** [comment]
Grazie.
Sto usando la V2 perchè non sono riuscito ad utilizzare la V1 ed ho visto
che c'era la 2...forse però sbagliavo troppe configurazioni.

si quindi x mosquitto metto IP di HA e per la porta, user e la PW?

...ci tengo ad integrare il termostato...è l'unica cosa che mi manca...

Grazie del supporto, mi mancano le basi per cavarmela senza un aiuto!

Massimo

Il giorno lun 9 nov 2020 alle ore 14:08 andrea-mattioli <
notifications@github.com> ha scritto:

**Comment by andrea-mattioli** [comment]
contattami su skype andrea.mattiols facciamo prima.
A.

**Comment by maxambro** [comment]
perfetto, grazie!
oggi non posso, ma domani provo.

Grazie per la disponibilità!
Massimo

Il giorno lun 9 nov 2020 alle ore 17:07 andrea-mattioli <
notifications@github.com> ha scritto:

**Comment by maxambro** [comment]
ciao e scusa se non mi sono più fatto vivo.
Durante il giorno, in settimana, ho qualche problema a chiamarti, ma se mi
dai una data ed un orario ci provo!
Ti allego un po' di miei HA setup.

Come posso supportare il tuo lavoro? Grande stima a chi si spende per la
comunità!
Hai un conto paypal?

Grazie
Massimo

Il giorno lun 9 nov 2020 alle ore 17:07 andrea-mattioli <
notifications@github.com> ha scritto:

**Comment by andrea-mattioli** [comment]
Gli account sono tutti sul readme!

[![Sponsor Mattiols via GitHub Sponsors](https://raw.githubusercontent.com/andrea-mattioli/bticino_X8000_rest_api/test/screenshots/sponsor.png)](https://github.com/sponsors/andrea-mattioli)

🍻 [![Sponsor Mattiols via paypal](https://www.paypalobjects.com/webstatic/mktg/logo/pp_cc_mark_37x23.jpg)](http://paypal.me/mattiols)

per la data a me andrebbe meglio la mattina quando vuoi tranne nel weekend

**Comment by maxambro** [comment]
Perfetto, grazie.
Domani vedo come inizia la settimana e ti faccio sapere.

Ok per PayPal!👍

Buona Domenica
Massimo

Il dom 15 nov 2020, 13:01 andrea-mattioli <notifications@github.com> ha
scritto:

**Comment by maxambro** [comment]
Ciao, rieccomi.
Ho aggiornato l'add-on, vedo i log, ma non sembra aggiornarsi la grafica
dei termostati. Ho fatto rebuilt, ma poi non mi funziona la web-ui. Mi
ricordo che avevi avuto anche tu dei problemi...
Cosa posso provare?

Grazie
Massimo

Il dom 15 nov 2020, 14:34 massimo ambrosino <maxambro@gmail.com> ha scritto:

**Comment by andrea-mattioli** [comment]
Sulla webui ci arrivi da browser http://192.168.1.x:5588 se usi https con duckdns o passi dall'esterno non ti funziona
A.

**Comment by maxambro** [comment]
Perfetto, grazie.
ora tutto è tornato a funzionare!

Saluti
Massimo

Il giorno lun 14 dic 2020 alle ore 08:18 andrea-mattioli <
notifications@github.com> ha scritto:
