### ISSUE TITLE
Addon stops working

### ISSUE THREAD

**Issue by fenderislife** [andrea-mattioli/mattiols_hassio_repository#17]
Buongiorno Andrea, grazie mille per la repository.
L'addon funziona correttamente, ma una volta al giorno interrompe il funzionamento dandomi questa notifica:

![image](https://user-images.githubusercontent.com/50184742/103228993-682e7680-4932-11eb-806b-6504a7a26180.png)

Nel log dell'addon ho questo:

`192.168.1.122 - - [28/Dec/2020 17:17:03] "POST /callback HTTP/1.1" 500 -
[2020-12-28 17:18:51,013] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 738, in callback
    parse_response(request.data)
  File "bticino.py", line 686, in parse_response
    chronothermostats_stored=load_api_config_arg("chronothermostats")
  File "bticino.py", line 156, in load_api_config_arg
    arg = json_object['api_requirements']['chronothermostats']
TypeError: 'NoneType' object is not subscriptable`

Se può essere utile, quando funziona normalmente alterna i callback del mio IP a questi:

`137.117.138.168 - - [22/Dec/2020 22:23:13] code 400, message Bad request syntax ("\x16\x03\x01\x01\x17\x01\x00\x01\x13\x03\x03ÕXò-\x95«'éñ¦?\x17ÕÑçî_\x92}\x96çÔÁ#S^¬7´Ö=H\x00\x00pÀ/À+À0À,\x00\x9eÀ'\x00gÀ(\x00k\x00£\x00\x9fÌ©Ì¨ÌªÀ¯À\xadÀ£À\x9fÀ]ÀaÀWÀS\x00¢À®À¬À¢À\x9eÀ\\À`ÀVÀRÀ$\x00jÀ#\x00@À")
137.117.138.168 - - [22/Dec/2020 22:23:13] "ÕXò-«'éñ¦?ÕÑçî_}çÔÁ#S^¬7´Ö=HpÀ/À+À0À,À'gÀ(k£Ì©Ì¨ÌªÀ¯À­À£ÀÀ]ÀaÀWÀS¢À®À¬À¢ÀÀ\À`ÀVÀRÀ$jÀ#@À" HTTPStatus.BAD_REQUEST -
192.168.1.122 - - [22/Dec/2020 22:23:16] "POST /callback HTTP/1.1" 200 - `

Capirei se non funzionasse proprio, ma non capisco perchè funziona normalmente (tutta la procedura su LeGrand è ok).
Se faccio il restart e l'accesso alla WebGUI con get your code ottengo la finestra normalmente popolata. L'addon però non riparte; è necessario uno snapshot a uno stato precedente in cui era normalmente attivo. In questo modo riparte normalmente.

Grazie per l'aiuto. Se necessario per le regole di github posso scrivere in inglese.

**Comment by andrea-mattioli** [comment]
Ciao da quello che vedo sembra che tu stia usando l'https, tutto il traffico è interno tra l'addon ed HA quindi deve esse in chiaro in http, quel messaggio di errore viene generato quando il file sotto /config/.bticino_smarter/smarter.json è vuoto.
è strano che devi riprendere una snap per farlo funzionare, non vorrei che ti si è installato male qualcosa.
Prova a fare il reload dei repository e poi fare un rebuild dell'addon.
e controlla che non stai usando https sull'indirizzo locale.
A.

**Comment by fenderislife** [comment]
Si, sto utilizzando https in locale. L ha configurato così l add-on duckdns e non so come fare per riportarlo http. Scusa in anticipo per le problematiche da niubbo

**Comment by andrea-mattioli** [comment]
puoi usare l'altro mio addon reverse proxy così puoi avere l'http in locale ed utilizzarlo anche con l'app:
https://hassiohelp.eu/2020/12/07/reverse-proxy-per-duckdns-home-assistant/
mi raccomando cancella i certificati di duck dal config.yaml

**Comment by fenderislife** [comment]
Fatto!
Ho cancellato 
`http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem `
da configuration.yaml
e ho fatto NAT 80 esterna su 80 interna e 443 esterna su 443 interna sull'ip di HA.

Per fare accesso dall'esterno della rete domestica ho dovuto togliere :8123 dall'indirizzo mionome.duckdns.org (anche la porta 8123 è nattata su sè stessa).

Non riesco ad accedere all'indirizzo duckdns dalla mia rete domestica, ma questo è un problema che esula dal tuo addon.

Grazie mille per il supporto

**Comment by andrea-mattioli** [comment]
no non devi esporre la 8123 ci pensa l'addon a girare le porte dalla 443 alla 8123.
la 8123 la devi usare solo dall'interno
A

**Comment by fenderislife** [comment]
Grazie mille!

**Comment by fenderislife** [comment]
Ciao Andrea,
pensavo di aver risolto con le tue indicazioni (messo il tuo reverse proxy, tolto addon duckdns) ma mi si ripresenta almeno una volta al giorno l'errore che già ti ho descritto.
Ora ovviamente l'accesso dal mio ip interno è su http, non più https, ma continuo a visualizzare:
1. il callback di 137.117.138.168 con errore 400 quando funziona normalmente, alternato ai callback normali del mio ip
2. l'errore killer quando si pianta, che mi costringe al ripristino dell'ultimo snapshot funzionante.
Altre idee per aiutarmi?
Grazie
Andrea

**Comment by andrea-mattioli** [comment]
Hai la porta 5588 aperta dall'esterno non devono esserci ip pubblici su quella porta chiudila la versione v2 non serve aprirla

**Comment by fenderislife** [comment]
Ho chiuso la porta e i callback ora sono perfetti.
Purtroppo stanotta mi ha ridato l'errore:

[2021-01-04 08:30:22,334] ERROR in app: Exception on /callback [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 738, in callback
    parse_response(request.data)
  File "bticino.py", line 686, in parse_response
    chronothermostats_stored=load_api_config_arg("chronothermostats")
  File "bticino.py", line 156, in load_api_config_arg
    arg = json_object['api_requirements']['chronothermostats']
TypeError: 'NoneType' object is not subscriptable
192.168.1.122 - - [04/Jan/2021 08:30:22] "POST /callback HTTP/1.1" 500 -

Ho proceduto, invece che al ripristino dello snapshot, al riavvio dell'addon e a fare "get your code" da Legrand.
Ottengo un riavvio normale dal LOG, con callback regolari.
L'addon riceve normali aggiornamenti dal termostato (se imposto modalità manuale dal termostato o dall'app ticino l'addon si aggiorna) ma non invia comandi al termostato.

Grazie
Andrea

**Comment by andrea-mattioli** [comment]
Cancellalo e reinstalla pulito non usare lo snapshots basta che ti salvi i dati fai copia incolla sulla configurazione

**Comment by andrea-mattioli** [comment]
aggiorna alla nuova versione dovrebbe aver risolto

**Comment by fenderislife** [comment]
Ciao Andrea,
non riesco ad aggiornare. Se faccio update da Supervisor non ho nessun risultato.
Se disinstallo l'addon e provo a installare la 2.4 (l'ho fatto sia senza intervenire su config.yaml sia cancellando la cartella .bticino_smarter in /config mi esce questo messaggio di errore

The command '/bin/ash -o pipefail -c apk add --no-cache bash tzdata python3 py3-pip git mosquitto-clients && git clone -b v2 https://github.com/andrea-mattioli/bticino_X8000_rest_api.git && mv bticino_X8000_rest_api/* /hassio_bticino_smarter/ && rm -rf bticino_X8000_rest_api/' returned a non-zero code: 4

Dove sbaglio?

**Comment by andrea-mattioli** [comment]
hai qualche problema su supervisor perchè il build ti deve andare a buon fine...
Che versione di HA stai usando?

**Comment by fenderislife** [comment]
L'ultima, ma avevo già provato ad aggiornare con la precedente senza risultati. Il tuo add-on proxy si è aggiornato senza problemi...

**Comment by andrea-mattioli** [comment]
Non è possibile che non ti fa la build, mandami su skype un team-viewer così con i dati che mi hai mandato non riesco a capire il problema skype: andrea.mattiols

**Comment by andrea-mattioli** [comment]
Fornisci un feedback o il ticket verrà chiuso in 24h

**Comment by fenderislife** [comment]
Hai ragione, ti chiedo scusa ma è un periodaccio. Se preferisci chiudo il ticket. Grazie ancora
