### ISSUE TITLE
unregistered webhook mattiols_x_8000

### ISSUE THREAD

**Issue by yashijoe** [andrea-mattioli/mattiols_hassio_repository#18]
Hello Andrea,

as I'm going to change my Smartert Bticino, I've unistalled your -great- addon from home assistant.
But I still got this message in the log:

Logger: homeassistant.components.webhook
Source: components/webhook/__init__.py:84
Integration: Webhook (documentation, issues)
First occurred: 9:23:17 (167 occurrences)
Last logged: 12:51:16

Received message for unregistered webhook mattiols_x_8000 from 172._XX.XX.XX_

Is there something more I should do?
Thank you
Kind regards

**Comment by yashijoe** [comment]
It seems I've solved deleting my Legrand account

**Comment by andrea-mattioli** [comment]
Hi you must remove c2c subscription from legrand.
you can use legrand's api (https://portal.developer.legrand.com/docs/services/smartherV2/operations/Get-subscriptions-to-C2C-notifications, https://portal.developer.legrand.com/docs/services/smartherV2/operations/Delete-subscription-to-C2C-notifications) or through my addon remove the subscription.
Then remove packages inside /config/packages/

Regards

Regards
