### ISSUE TITLE
Unit of measurement

### ISSUE THREAD

**Issue by gobbe87** [andrea-mattioli/mattiols_hassio_repository#19]
Hello Andre,
Thank you very much for your work on this addon, really a grate job!!

Can I know why you don't use unit of measurement in the temperature?

I try to add "unit_of_measurement: °" on the #temperature sections and I can have automatically the graph on lovlace  interface.

Thank you, Alberto

**Comment by andrea-mattioli** [comment]
I will add it to the new release, if you want to add it just edit the packages " /config/packages/bticino_x8000.yaml ", and add " **unit_of_measurement: '°C'** " on temperature sensor:

```   ### temperature
  - platform: mqtt
    name: termostato_XXX_temperature
    state_topic: /bticino/XXXXXXXXXXXXXXXXXXXX/status
    value_template: '{{ value_json.temperature }}'
    unit_of_measurement: '°C'
    icon: mdi:thermometer

**Comment by gobbe87** [comment]
> I will add it to the new release, if you want to add it just edit the packages " /config/packages/bticino_x8000.yaml ", and add " **unit_of_measurement: '°C'** " on temperature sensor:
> 
> ```
>   - platform: mqtt
>     name: termostato_XXX_temperature
>     state_topic: /bticino/XXXXXXXXXXXXXXXXXXXX/status
>     value_template: '{{ value_json.temperature }}'
>     unit_of_measurement: '°C'
>     icon: mdi:thermometer
> ```

Thank you! I already done the configuration :)
