### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by gpanni77** [andrea-mattioli/mattiols_hassio_repository#2]
Buongiorno,
ho un Raspberry Pi 4 Model B con Raspbian e con hassio 0.109.4 che gira in un docker container raggiungibile tramite https://********.duckdns.org con relativo certificato di sicurezza SSL.

Ho configurato il tutto e ottengo questo log alla partenza (sembra tutto ok):

_[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020/05/06 21:07:48 [notice] 261#261: using the "epoll" event method
2020/05/06 21:07:48 [notice] 261#261: nginx/1.16.1
2020/05/06 21:07:48 [notice] 261#261: OS: Linux 4.19.86-v7l+
2020/05/06 21:07:48 [notice] 261#261: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/05/06 21:07:48 [notice] 261#261: start worker processes
2020/05/06 21:07:48 [notice] 261#261: start worker process 263
/ssl/fullchain.pem /ssl/privkey.pem
[21:07:48] INFO: certificate found!
2020/05/06 21:07:48 [notice] 261#261: signal 15 (SIGTERM) received from 177, exiting
2020/05/06 21:07:48 [notice] 263#263: exiting
2020/05/06 21:07:48 [notice] 263#263: exit
2020/05/06 21:07:48 [notice] 261#261: signal 14 (SIGALRM) received
2020/05/06 21:07:48 [notice] 261#261: signal 17 (SIGCHLD) received from 263
2020/05/06 21:07:48 [notice] 261#261: worker process 263 exited with code 0
2020/05/06 21:07:48 [notice] 261#261: exit
[21:07:48] INFO: Setup config file...
2020/05/06 21:07:48 [notice] 273#273: using the "epoll" event method
2020/05/06 21:07:48 [notice] 273#273: nginx/1.16.1
2020/05/06 21:07:48 [notice] 273#273: OS: Linux 4.19.86-v7l+
2020/05/06 21:07:48 [notice] 273#273: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2020/05/06 21:07:48 [notice] 273#273: start worker processes
2020/05/06 21:07:48 [notice] 273#273: start worker process 279
Serving Flask app "bticino" (lazy loading)
Environment: production
WARNING: This is a development server. Do not use it in a production deployment.
Use a production WSGI server instead.
Debug mode: off
Running on http://127.0.0.1:5555/ (Press CTRL+C to quit)
[21:07:51] INFO: Api address: https://********.duckdns.org:5588/_

Quando però premo "Get You Code", immetto le credenziali Legrand e premo "Accetta" compare il seguente errore:

_Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application._

Nel Log compare questo:

_127.0.0.1 - - [06/May/2020 21:31:36] "GET / HTTP/1.1" 200 -
2.36.84.9 - admin [06/May/2020:21:31:36 +0200] "GET / HTTP/1.1" 200 874 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
[2020-05-06 21:31:43,103] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 571, in callback
    access_token, refresh_token = get_access_token(code)
  File "bticino.py", line 193, in get_access_token
    access_token = json.loads(response.text)['access_token']
KeyError: 'access_token'
127.0.0.1 - - [06/May/2020 21:31:43] "GET /callback?code=XXXXXXXXX&state=XXXXXXXXX HTTP/1.1" 500 -
2.36.84.9 - admin [06/May/2020:21:31:43 +0200] "GET /callback?code=XXXXXXXXX&state=XXXXXXXX HTTP/1.1" 500 290 "https://partners-login.eliotbylegrand.com/consent?guid=XXXXXXXX" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"_

Cosa può essere?

Grazie

**Comment by andrea-mattioli** [comment]
Il problema è che non riesce a scaricare correttamente i dati del suo termostato da Legrand.

1.  Ha configurato correttamente l'app con le abilitazioni sugli scope descritti in guida?
2. La mail di registrazione che ha usato per l'account Legrand è la stessa che usa per gestire il termostato dall'app ufficiale della bticino?
3. Ha abilitato l'accesso terze parti dall'app ufficiale della bticino?
    APP --> Account --> ACCESSO TERZE PARTI

**Comment by gpanni77** [comment]
Si,
prima di scrivere qui, per scrupolo, avevo anche eseguito i passaggi di questo tutorial:
https://developer.legrand.com/tutorials/create-an-application-using-postman-v6-1-3/
E tutto funziona, ottengo l'access_token e il refresh_token.
Sono anche riuscito a leggere la temperatura tramite home assistant creando un rest sensor che però smette di funzionare dopo un'ora quando il token scade.

Ho un dubbio su cosa mettere nei campi "Url" e "First Reply Url".
Nella guida compare quanto segue:
Public Url = https://myDomain:5588/
First Reply Url = https://myDomain:5588/callback
Poi però nell'immagine subito sotto questo:
![image](https://user-images.githubusercontent.com/57314917/81264492-c9bb7100-9041-11ea-8ed4-eb624a00731d.png)
C'è "/rest/" in più.

Grazie

**Comment by andrea-mattioli** [comment]
E' uguale, il campo URL non viene usata per la gestione del token.
l'importante è First Reply Url che a quanto vedo è corretto.
Se è l'app di legrand è configurata bene, allora c'è qualche problema nella configurazione dell'add-on.
L'errore che restituisce è scaturito da un codice non valido ricevuto nella risposta da legrand , che quindi non gli permette poi di trovare l'access_token.
infatti riceve un 500 (internal sever error) durante la chiamata "GET" sulla /callback
Controlli sulle configurazioni dell'add-on:
```
client_id: 216******************4f837a --> (ricevuto via email)
client_secret: 'Uu********************4tfl' --> (ricevuto via email)
subscription_key: f38***********ad7 --> (valore della Primary key del portale legrand my subscription)
domain: 'domain.duckdns.org' --> (solo DOMINIO senza https:// e porta finale)
```

**Comment by gpanni77** [comment]
Grazie,
grazie del suggerimento, credo di aver capito il problema.
Il mio client_secret contiene all'interno un doppio backslash, per intenderci è così:
e9)\\_2XXXXXXXXXXXXXXXXXX
E appena salvo la configurazione dell'addon si trasforma così:
e9)\_2XXXXXXXXXXXXXXXXXX
Cioè rimane un solo backslash.
Ho provato a  mettere il client_secret tra apici singoli o doppi apici ma, appena salvo, questi vengono rimossi e il doppio backslash viene sostituito da un singolo backslash.
Come si può risolvere?

Grazie

**Comment by andrea-mattioli** [comment]
Ho provato sulla mia installazione e a me inserisce e salva correttamente i 2 backslash.
Supervisor Version = 220
Home Assistant = 0.109.4
versione add_on = 0.2

![image](https://user-images.githubusercontent.com/5707570/81275686-4e15f000-9052-11ea-8869-a0537711c4f7.png)


Comunque provi ad aggiungere \ ad esempio metterne 3 di backslash
\\\\\\
probabilmente il parser della configurazione di home assistant lo interpreta come "escape character"

**Comment by gpanni77** [comment]
Buongiorno,
ho provato in tutti i modi senza riuscirci.
Ho quindi creato una nuova applicazione su Legrand e fortunatamente il client_secret non ha più il doppio backslash all'interno.
Ora, con questa nuova applicazione, tutto funziona.

Grazie

**Comment by andrea-mattioli** [comment]
Ok, magari se mi dice le versioni di homeassistant e supervisor riesco a simulare il problema e fixarlo nelle successive versioni.

**Comment by gpanni77** [comment]
Ho un Raspberry Pi 4 Model B con Raspbian e con hassio 0.109.4 che gira in un docker container raggiungibile tramite https://********.duckdns.org con relativo certificato di sicurezza SSL.
La versione del supervisor è la 220.

La cosa strana è che anche a me apparentemente il client_secret era a posto appena premevo "Save", poi però appena cambiavo pagina e tornavo sulla configurazione ecco che trovavo il doppio backslash sostituito con uno singolo.
Dopo un po' di tentativi (non so come) sono riuscito a far rimanere fisso il doppio backslash ma ottenevo comunque l'errore.
Penso comunque che sia un evento più unico che raro avere il doppio backslash nel client_secret.

Scusi, le faccio un'altra domanda, poi mi dica lei se è il caso di aprire una nuova issue.
Ho notato che i messaggi vengono pubblicati sul broker mqtt in modo inusuale:
![image](https://user-images.githubusercontent.com/57314917/81307582-1ffbd480-9081-11ea-8701-3cf98befe6fa.png)
Cioè, il primo livello è senza nome.
Tutto funziona lo stesso ma mi chiedevo il motivo.

Grazie

**Comment by andrea-mattioli** [comment]
Sono 2 clientid differenti provenienti dallo stesso indirizzo, solo che uno apre e chiude la chiamata quando arrivano i dati l’altro rimane sempre attivo.
Probabilmente è per quello
