### ISSUE TITLE
Addon not working after last update

### ISSUE THREAD

**Issue by Tinwelint78** [andrea-mattioli/mattiols_hassio_repository#20]
Buongiorno Andrea,
dopo l'ultimo aggiornamento l'addon ha smesso di funzionare.
Ho seguito la solita procedura, ho cancellato la cartella .bticino_smarter in config, ho fatto un rebuild, e poi in https://my_hassio_ip:5588/ ho seguito la procedura per generare il codice. Quando premo "accetta", però, mi porta in una pagina di errore (500 internal server error).
Il log di home assistant mi riporta:
`[11:04:52] INFO: Api address: https://xxxxxx.duckdns.org:5588/
127.0.0.1 - - [11/Feb/2021 11:04:53] "GET / HTTP/1.1" 401 -
xxx.xxx.xxx.xxx - - [11/Feb/2021:11:04:53 +0100] "GET / HTTP/1.1" 401 19 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
127.0.0.1 - - [11/Feb/2021 11:04:55] "GET / HTTP/1.1" 200 -
xxx.xxx.xxx.xxx - xxxxx@xxxxx [11/Feb/2021:11:04:55 +0100] "GET / HTTP/1.1" 200 877 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
127.0.0.1 - - [11/Feb/2021 11:04:55] "GET /favicon.ico HTTP/1.1" 404 -
xxx.xxx.xxx.xxx - xxxx@xxxxx [11/Feb/2021:11:04:55 +0100] "GET /favicon.ico HTTP/1.1" 404 209 "https://xxxx.duckdns.org:5588/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0"
[2021-02-11 11:05:06,519] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 331, in get_topology
    Null,programs=get_programs_name(access_token, plant, topologyid)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 760, in callback
    chronothermostats=get_topology(access_token,my_plants)
  File "bticino.py", line 335, in get_topology
    print("[Errno {0}] {1}".format(e.errno, e.strerror))`

ho ripetuto più volte la procedura ma l'errore rimane sempre lo stesso.

**Comment by andrea-mattioli** [comment]
quale versione stai usando la V.2?
hai fatto rebuild dopo l'aggiornamento?

**Comment by Tinwelint78** [comment]
Sto usando la V.1, sì ho fatto rebuild

**Comment by Tinwelint78** [comment]
consigli di usare la V2?

**Comment by andrea-mattioli** [comment]
assolutamente si... la v1 è in end of support metti la V2, controlla le modifiche da apportare sull'app di legrand 
https://hassiohelp.eu/2020/05/01/bticino-smarther-x8000/

**Comment by Tinwelint78** [comment]
Ho installato la V2, ho fatto le modifiche all'app Legrand, ma mi da lo stesso identico errore quando tento di generare il codice. Il log è identico:
[2021-02-12 08:33:52,258] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 332, in get_topology
    Null,programs=get_programs_name(access_token, plant, topologyid)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 745, in callback
    chronothermostats=get_topology(access_token,my_plants)
  File "bticino.py", line 336, in get_topology
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'TypeError' object has no attribute 'errno'

Potrebbe essere qualcosa nella mia installazione di home assistant, visto che fra V1 e V2 non è cambiato nulla nell'errore?

**Comment by Tinwelint78** [comment]
Questo è il mio setup
## System Health

version | core-2021.2.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v7l
arch | armv7l
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4967
Installed Version | 1.11.2
Stage | running
Available Repositories | 744
Installed Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.11
-- | --
update_channel | stable
supervisor_version | supervisor-2021.02.6
docker_version | 19.03.13
disk_total | 57.8 GB
disk_used | 5.8 GB
healthy | true
supported | true
board | rpi4
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.2.0), Node-RED (8.1.1), SSH & Web Terminal (8.0.1), Mosquitto broker (5.1), Samba share (9.3.0), TasmoAdmin (0.14.0), Duck DNS (1.12.5), Bticino X8000 v2 (2.4)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 0
mode | auto-gen

</details>

**Comment by andrea-mattioli** [comment]
non è che hai disabilitato dall'app l'accesso 3e parti?

**Comment by Tinwelint78** [comment]
no... però mi puoi chiarire una cosa? Io ho duckdns e letsencript, quindi "esternamente" il mio homeassistant è raggiungibile su un indirizzo duckdns tramite https, con la porta standard 443 (che ho reindirizzato sul router alla 8123). Nella App Legrand alla voce "First reply url" devo mettere l'indirizzo ip della rete interna (con http) o l'indirizzo esterno duckdns (con https)?
Al momento ho messo:
http://192.168.1.88:5588/callback (che è l'indirizzo locale dell'homeassistant)
visto che se mettevo:
https://xxxxx.duckdns.org:5588/callback
poi mi dava errore in fase di creazione del codice (chiaramente la porta 5588 l'ho aperta sul router)
altra domanda, come "haip" nella configurazione dell'addon ho messo 192.168.1.88, corretto?

**Comment by andrea-mattioli** [comment]
Allora, per utilizzare http su l'indirizzo locale e usi duck devi mettere il mio proxy:
https://hassiohelp.eu/2020/12/07/reverse-proxy-per-duckdns-home-assistant/
così puoi cancellare 2 addon e lasciarne uno solo (occhio che devi rimuovere la parte inerente ai certificati dal config.yaml), il mio proxy gestisce in automatico i certificati e il cambio di indirizzo IP.
Per il proxy devi aprire la 80 Estena sulla 80 Locale, stessa cosa per la 443 Esterna su 443 Locale.
Per quanto riguarda l'addon V2 Bticino la porta 5588  NON deve esse aperta sul router.
La variabile HAIP è l'indirizzo ip interno di home assistant quindi si è corretto 192.168.1.88.

**Comment by Tinwelint78** [comment]
Ok, ho provato il reverse proxy, ma probabilmente ho sbagliato qualcosa nella configurazione... Al momento uso l'addon "Duckdns" e nel configuration.yaml ho queste linee:
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
Funziona da remoto in https ma chiaramente non in locale. Se attivo il reverse proxy, disattivo l'addon duckdns e tolgo completamente la voce http nel configuration.yaml, mi funziona in locale in http ma smette di funzionare dal lato duckdns (si connette ma dice "Unable to connect to Home Assistant." Devo mettere qualcosa di diverso sotto la voce "http:"?

**Comment by andrea-mattioli** [comment]
non devi mettere nulla sotto la voce http, fa tutto il reverse proxy.
tu devi aprire solo la porta 80 esterna verso HA e la porta 443 esterna verso HA.
la porta 8123 NON deve essere ne aperta ne girata dall'esterno ma solo interno

**Comment by Tinwelint78** [comment]
Errore mio, avevo la porta 443 indirizzata alla 8123! Ora il reverse proxy funziona perfettamente. L'errore sull'addon Bticino sfortunatamente è rimasto...

**Comment by Tinwelint78** [comment]
il traceback è identico a prima

**Comment by andrea-mattioli** [comment]
Il termostato lo vedi bene dall'app ufficiale?
hai usato la stessa mail di registrazione sul sito di legrand?
hai controllato l'accesso 3e parti se è abilitato correttamente?
Hai messo tutti i dati corretti nella configurazione dell'addon?

**Comment by Tinwelint78** [comment]
> Il termostato lo vedi bene dall'app ufficiale?

Sì certo

> hai usato la stessa mail di registrazione sul sito di legrand?

assolutamente sì. A questo proposito, nell'addon V1 si inseriva nelle impostazioni api user e password, ma nel nuovo non ci sono più, è corretto?

> hai controllato l'accesso 3e parti se è abilitato correttamente?

è abilitato

> Hai messo tutti i dati corretti nella configurazione dell'addon?

penso, ho seguito le indicazioni. Ho verificato mille volte client id, secret e subscription key e sono corretti (anche perché non sono cambiati dalla precedente versione dell'addon, che funzionava...), domain è il mio indirizzo duckdns (senza porta perché utilizzo la 443 standard), haip e mqtt_broker l'ip locale dell'home assistant, mqtt_port è standard 1883, user e password sono corretti.

**Comment by andrea-mattioli** [comment]
ho rilasciato una nuova versione con autologin vedi se ti funziona altrimenti facciamo una sessione teamviewer e vedo direttamente.

**Comment by Tinwelint78** [comment]
Ho provato l'ultimo aggiornamento, ma mi da errore subito nel tentativo di autologon:

[08:54:55] INFO: Trying autologin to Legrand...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "login.py", line 20, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

Sembra che gli manchi qualcosa nel path, come faccio ad aggiungerlo?

**Comment by andrea-mattioli** [comment]
possiamo fare una sessione team viewer?
non riesco a capire come mai hai tutti questi problemi durante l'installazione.
scrivimi su skype andrea.mattiols

**Comment by Tinwelint78** [comment]
No problem, ho scoperto cosa non andava. Per la cronaca, colpa di un'automazione che avevo aggiunto per gestire i webhook di IFTTT: era scritta scorrettamente e mi reindirizzava tutti i webhook, anche quelli dell'addon!
