### ISSUE TITLE
Addon Sometimes Doesn't send command

### ISSUE THREAD

**Issue by Steve707-AE** [andrea-mattioli/mattiols_hassio_repository#21]
Ciao, ti contatto dopo aver avuto qualche problema con l'add-on. Sto usando la versione V2 dell'addon, con rete locale in http usando nginx. Se vado su info nell'API mi segna tutti gli stati del termostato anche in tempo reale quando li cambio dall'app ufficiale, ma a volte quando cerco di cambiare temperatura non prende il comando, ho provato anche a postare un mqtt direttamente ma niente non cambia. L'errore è questo:

192.168.0.9 - - [15/Feb/2021 18:10:23] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..d4LdS1g-H0nxeC3J.Tx5TJAo8ish1tFFRgacZwoyJXqCQImSOKJUGQ72AYNoSVsKlii7PqII34UzkLmKVEgXqzSfCcagmhc50xpkqupuJe6NbwmasSUE1PY4p0Fn3dEhmcx0ze9mM_wmUk8qAJr8IFTGeMEbuPF2UUsar2G_PQeX4txS4U9m5uOVJGKR7KsGvi-SLGJWiB5tkeJgw4FjxnC1OxyrMW_Qk-aRFIL0W-iUeJGYl0d2t9NWKXhzG8epogRRx8Jz4f-mvVaq2lsMPJ1buv9d7F0wHz3mGW4c3nRLWADw1m3ZsIgEZgTMNkVyqEn9o1ML5rXJSis67-RG6Fh6TII_JYe-anWbByGnY3TfStS0uD1fQ1jp79u6NSGPxPrIqBWxZcXyaPwAN2TCIx1dRlVM5Rx4GUCSw2m-gii4wekWDsWDFK3hPlHz4raYqYiahc49S6T_VrNlIifa4rolTprzwWiEa7c85B5dtfMNPG_0QQE3jTJytAdTaO6OGtRQCbotGs2BhULJ39PZvcSKuWE5wIcPgFPqWPBIoIfSBFKwNoahYE5sGh54c2ndUB16AfUA69bPsEKk1fueGcDAEOpXQU5Z5-3VH0DRQ0OpqznR3FDu9k-pjMfRnZnRAA3zSAawY67KS4_5EwMT9o_ZW1flc4cw8BHO14km-Fehd8xmhj7f1366v-umikIXp5CrZuSqkta2yqwiH28DUeSI53meZgxXUjBagwF0Li3cCS51BLUHR7Q1vZtlCjRGgy_Xuo8luNYy0f2YPkQVpHYsyes41wAZo3GwF8-xLF2qPh3Ii_uXJuViByCEGhX0wlxukK_5tTjAI3wuxzOK4qPYJHxbzcgVz_9IJIsZf4jXuckk5grCN_Mq2Z595XHgDBVz0mryO.65MFaRY78shTERxWcBZV6w&state=G0vsOQAd8Ijc9VRp9lfpquKutIRHSJBB HTTP/1.1" 500 -
[2021-02-15 18:10:25,609] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 742, in callback
    access_token, refresh_token = get_access_token(code)
  File "bticino.py", line 268, in get_access_token
    access_token = json.loads(response.text)['access_token']
KeyError: 'access_token'
192.168.0.9 - - [15/Feb/2021 18:10:25] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..d4LdS1g-H0nxeC3J.Tx5TJAo8ish1tFFRgacZwoyJXqCQImSOKJUGQ72AYNoSVsKlii7PqII34UzkLmKVEgXqzSfCcagmhc50xpkqupuJe6NbwmasSUE1PY4p0Fn3dEhmcx0ze9mM_wmUk8qAJr8IFTGeMEbuPF2UUsar2G_PQeX4txS4U9m5uOVJGKR7KsGvi-SLGJWiB5tkeJgw4FjxnC1OxyrMW_Qk-aRFIL0W-iUeJGYl0d2t9NWKXhzG8epogRRx8Jz4f-mvVaq2lsMPJ1buv9d7F0wHz3mGW4c3nRLWADw1m3ZsIgEZgTMNkVyqEn9o1ML5rXJSis67-RG6Fh6TII_JYe-anWbByGnY3TfStS0uD1fQ1jp79u6NSGPxPrIqBWxZcXyaPwAN2TCIx1dRlVM5Rx4GUCSw2m-gii4wekWDsWDFK3hPlHz4raYqYiahc49S6T_VrNlIifa4rolTprzwWiEa7c85B5dtfMNPG_0QQE3jTJytAdTaO6OGtRQCbotGs2BhULJ39PZvcSKuWE5wIcPgFPqWPBIoIfSBFKwNoahYE5sGh54c2ndUB16AfUA69bPsEKk1fueGcDAEOpXQU5Z5-3VH0DRQ0OpqznR3FDu9k-pjMfRnZnRAA3zSAawY67KS4_5EwMT9o_ZW1flc4cw8BHO14km-Fehd8xmhj7f1366v-umikIXp5CrZuSqkta2yqwiH28DUeSI53meZgxXUjBagwF0Li3cCS51BLUHR7Q1vZtlCjRGgy_Xuo8luNYy0f2YPkQVpHYsyes41wAZo3GwF8-xLF2qPh3Ii_uXJuViByCEGhX0wlxukK_5tTjAI3wuxzOK4qPYJHxbzcgVz_9IJIsZf4jXuckk5grCN_Mq2Z595XHgDBVz0mryO.65MFaRY78shTERxWcBZV6w&state=G0vsOQAd8Ijc9VRp9lfpquKutIRHSJBB HTTP/1.1" 500 -
192.168.0.9 - - [15/Feb/2021 18:11:00] "GET / HTTP/1.1" 200 -
192.168.0.9 - - [15/Feb/2021 18:11:03] "GET /info HTTP/1.1" 200 -
192.168.0.30 - - [15/Feb/2021 18:11:41] "POST /callback HTTP/1.1" 200 -
192.168.0.30 - - [15/Feb/2021 18:13:08] "POST /callback HTTP/1.1" 200 -
192.168.0.30 - - [15/Feb/2021 18:14:39] "POST /callback HTTP/1.1" 200 -
192.168.0.30 - - [15/Feb/2021 18:16:46] "POST /callback HTTP/1.1" 200 -
192.168.0.30 - - [15/Feb/2021 18:17:00] "POST /callback HTTP/1.1" 200 -
192.168.0.9 - - [15/Feb/2021 18:18:05] "GET /info HTTP/1.1" 200 -
192.168.0.9 - - [15/Feb/2021 18:18:07] "GET /info HTTP/1.1" 200 -

Come ripeto, gli stati li vede tutti e perfettamente, ma non invia i comandi. Ho provato a fare rebuild e i primi comandi li ha presi, ma dopo ha rifatto il problema.

**Comment by andrea-mattioli** [comment]
Rimuovi la directory /config/.bticino_smarter/
fai il rebuild dell'addon e poi la procedura get your code

**Comment by Steve707-AE** [comment]
Fatto ieri sera, sta mattina sono entrato in ha e c'erano 4 notifiche dell'addon "Error, click to get your code"

**Comment by andrea-mattioli** [comment]
aggiorna all'ultima versione vedi se risolvi

**Comment by andrea-mattioli** [comment]
Fornisci un feedback o chiudo la segnalazione entro 24h
