### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by almico** [andrea-mattioli/mattiols_hassio_repository#23]
First of all, thank you for your work 😃 
I'm struggling a bit to decipher what to write and where to use your add-on. I read the italian article (updated this January) and it contains even more misleading information.
Let me describe what I think should be improved in your "bticino_X8000" readme page:

The page first states this:
![image](https://user-images.githubusercontent.com/15247405/108621013-577d1700-7430-11eb-811b-34b05ddc7de2.png)

But, a few lines later, it states this:
![image](https://user-images.githubusercontent.com/15247405/108620591-62827800-742d-11eb-803d-2aa3a1dd9fe7.png)

What should be entered in the "Url"?
- "https://somedomain.duckdns.org:5588"
- "https://somedomain.duckdns.org:443"
- "https://somedomain.duckdns.org:5588/rest"
- "https://somedomain.duckdns.org:443/rest"

What's the meaning of "myWebServerPort"? Because I am exposing my HA to the public on the standard https (443) port, not 5588. Should I use 443 for "myWebServerPort", thus: wherever I read 5588 in the readme?

The answer about the port would help me understand if a new web server (on port 5588, I would assume) is going to be created by your add-on or if any other setup is used (which one?).

In general, I fear there are some assumptions about the existing HA configuration that I am missing. For example: I use DuckDNS just to handle Let's Encrypt certificates and expose the internal IP to the outside World using Nginx (that enables https). Is this ok / irrelevant?

I also read, in the configuration section, the following line about `mqtt_port`:
![image](https://user-images.githubusercontent.com/15247405/108620840-09b3df00-742f-11eb-9b4a-61ccd56c90a1.png)

Is there any reason why there are single quotes there? I think, in a real configuration, that line should read `mqtt_port: 1883` with no quotes. Is this correct?
I am new to HA (I started 10 days ago), thus I'm not sure, but I think an MQTT Broker is not run by default. If I'm correct, I think you should clarify that as a prerequisite for your add-on to work.

In the meantime I have updated my application to Legrand with my new best bets about `Url` and `First Reply Url` and I'm waiting for a new approval 😄

**Comment by andrea-mattioli** [comment]
Hi please use V2 version the other it's end of life!
follow this guide:
https://hassiohelp.eu/2020/05/01/bticino-smarther-x8000/

Thanks

**Comment by almico** [comment]
Thank you for your answer ❤️

Looking at the article you referenced:

![image](https://user-images.githubusercontent.com/15247405/108623135-982f5d00-743d-11eb-975c-35e37d31d711.png)

I think I should enter my public IP, like `somedomain.duckdns.org` and not `192.168.x.y`. Is this correct?
I still also wonder if I should enter 5588 or 443 (I expose my HA using HTTPS on port 443 through Nginx).

Do you also confirm that `Url` should be set to `https://github.com/andrea-mattioli/mattiols_hassio_repository`?

**Comment by andrea-mattioli** [comment]
No you must enter local ip 192.168.x.y because with the v2 version you don't need any ports open on your router.
You must close 5588 on your router, v2 version receive data through HA's webhook.
if you want remove nginx you can use my reverse proxy:
https://hassiohelp.eu/2020/12/07/reverse-proxy-per-duckdns-home-assistant/

**Comment by almico** [comment]
> On the first url you can add all you want!

😨 
Do you mean that it is totally useless / unused? I could even set `Url` to "Antani"? 😄

**Comment by andrea-mattioli** [comment]
Yes is unused!
https://comesefosseantani.com, but use a real url i'don't know if they do a reachbility check!

**Comment by andrea-mattioli** [comment]
can i close this issues?

**Comment by almico** [comment]
Yes 🥰
