### ISSUE TITLE
Entità climate.termostato non trovata 

### ISSUE THREAD

**Issue by Simonee88** [andrea-mattioli/mattiols_hassio_repository#24]
Buongiorno, ho di recente installato questo addon, ho seguito tutti i passaggi sulla documentazione e di per se funziona, infatti se vado su ip:5588 mi escono le informazioni del mio termostato il problema è che home assistant non rileva l'entità, la configurazione di mqqt è corretta e nel log non ci sono errori

**Comment by andrea-mattioli** [comment]
Try this config on mqtt.yaml 

~ $ cat config/mqtt.yaml 

### MOSQUITTO ON HASSIO ###
broker: !secret mqtt_broker
username: !secret mqtt_hassio_user
password: !secret mqtt_hassio_pwd
discovery: true
discoveryprefix: hassio_

**Comment by andrea-mattioli** [comment]
ok but must have the mqtt configuration inside configuration.yaml

**Comment by Simonee88** [comment]
![image](https://user-images.githubusercontent.com/55895156/110652713-e7ef8180-81bc-11eb-9570-64f0afbecb6f.png)

**Comment by andrea-mattioli** [comment]
Te lo scrivo in Italiano che magari ci capiamo meglio 
Quelli sono gli include... se non hai mqtt.yaml non puoi avere nemmeno gli include ma la configurazione della classe mqtt: la devi avere altrimenti non ti può funzionare.
Metti la configurazione che ti ho passato e riavvia ha e poi mi dici se ti funziona

**Comment by andrea-mattioli** [comment]
provide feedback or close the ticket

**Comment by Simonee88** [comment]
Scusa non avevo avuto modo di provare.. ha funzionato grazie
