### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Luke001IT** [andrea-mattioli/mattiols_hassio_repository#25]
Ciao Andrea

I did follow all the steps and I got the email from Bticino... 
I opened the configuration, added all the information as listed but when I open the web interface nothing happen... I think that the problem could be the domain of Hassio since I'm using Nabu casa... 

First question: in the bticino application, when I have to input the "first reply url", the url must finish with /callback ?
Shall I use the ip here or the domain of nabu casa?

Second question: in the supervisior configuration, at the domain, which url I should use?

I think that the problem is around this story of the domain since if I try to open the webui using the local ip address with port 5588, I arrive to the "get your corde" page, but when I click I get the error...

Can you help?

**Comment by andrea-mattioli** [comment]
Hi, i didn't try before with nabucasa!
could we schedule a remote session to try to solve this problem?
on the first reply url you must use your local ip address with /callback
ex http://192.168.1.x:5588/callback
Regards

**Comment by Luke001IT** [comment]
I've started over all the procedure and finally I arrived to this: 
![immagine](https://user-images.githubusercontent.com/64697208/114596661-2ed70800-9c90-11eb-9447-91a6ed89877e.png)

And finally to this: 
![immagine](https://user-images.githubusercontent.com/64697208/114596729-3f877e00-9c90-11eb-8631-1e2757f909bd.png)

But no information on the lovelace... Did I miss something?

**Comment by andrea-mattioli** [comment]
https://github.com/andrea-mattioli/mattiols_hassio_repository/issues/24

**Comment by Luke001IT** [comment]
I'm sorry but I need some more explaination... I dind't have the mqtt.yaml file, I've created a new one with this info: 
broker: !secret mqtt_broker
username: !secret mqtt_hassio_user
password: !secret mqtt_hassio_pwd
discovery: true
discoveryprefix: hassio_

Should I define the secret in the secrets.yaml file? Shall I add something also to the configuration.yaml? I've tried to find some info over the interent but honestly I couldn't find any...

All the tutorial over the internet show how to set-up mosquitto mqtt from supervisor (which i did) and then to find the integration and add it...

**Comment by andrea-mattioli** [comment]
Check the official documentation "https://www.home-assistant.io/integrations/mqtt/"
```
# Example configuration.yaml entry
mqtt:
  broker: "IP_ADDRESS_BROKER"
  username: "MQTT_USERNAME"
  password: !secret MQTT_PASSWORD
  discovery: true
  discovery_prefix: hassio_
```

**Comment by Luke001IT** [comment]
Scrivo in italiano che forse ci capiamo meglio...
MQTT l'ho aggiunto come integrazione, quindi non serve mettere questa parte nel configuration.yaml... è scritto anche nel documento che hai linkato...

Ora mi viene un grosso dubbio sull'IP del broker... Dove lo trovo? Ero convinto che corrispondesse con quello di hassio 192.168.... Magari è questo l'errore?

**Comment by andrea-mattioli** [comment]
L'ip del broker è quello di HA... per me il problema è il discovery e il prefix, altri hanno risolto con quella conf che ti ho mandato, io ce l'ho da sempre così e funziona

**Comment by Luke001IT** [comment]
Solved... I've re-set mosquitto mqtt to default setting and restart hassio... now is working!

**Comment by andrea-mattioli** [comment]
great
