### ISSUE TITLE
Fail to install v2.6

### ISSUE THREAD

**Issue by gpanni77** [andrea-mattioli/mattiols_hassio_repository#26]
Hello Andrea,
I have a raspberry pi 4 model B with raspbian installed and home assistant running in docker.
Everything is updated to the latest versions, Raspbian GNU/Linux 10 (buster), core-2021.4.5, supervisor-2021.04.0, Docker version 20.10.2
When I try to install I see the following in the log, can you help me please?

```
21-04-18 17:42:45 INFO (SyncWorker_4) [supervisor.docker.addon] Starting build for d5113cf9/armv7-addon-smarter_x8000_v2:2.6
21-04-18 17:43:02 ERROR (SyncWorker_4) [supervisor.docker.addon] Can't build d5113cf9/armv7-addon-smarter_x8000_v2:2.6: The command '/bin/ash -o pipefail -c /bin/ash -c 'set -ex &&     ARCH=`uname -m` &&     if [ "$ARCH" == "armv7l" ] || [ "$ARCH" == "armhf" ]; then         apk add --no-cache            bash            tzdata            python3            py3-pip            git            mosquitto-clients                    && git clone -b v2 https://github.com/andrea-mattioli/bticino_X8000_rest_api.git         && mv bticino_X8000_rest_api/* /hassio_bticino_smarter/         && rm -rf bticino_X8000_rest_api;     else         apk add --no-cache            bash            tzdata            python3            py3-pip            git            mosquitto-clients            chromium            chromium-chromedriver                    && git clone -b v2 https://github.com/andrea-mattioli/bticino_X8000_rest_api.git         && mv bticino_X8000_rest_api/* /hassio_bticino_smarter/         && rm -rf bticino_X8000_rest_api;     fi'' returned a non-zero code: 4
21-04-18 17:43:02 ERROR (SyncWorker_4) [supervisor.docker.addon] Build log: 
Step 1/15 : ARG BUILD_FROM


Step 2/15 : FROM $BUILD_FROM


 ---> 32848b90eab5

Step 3/15 : RUN mkdir /hassio_bticino_smarter


 ---> Using cache

 ---> 885aa0c27544

Step 4/15 : WORKDIR /hassio_bticino_smarter


 ---> Using cache

 ---> aa5045285633

Step 5/15 : RUN /bin/ash -c 'set -ex &&     ARCH=`uname -m` &&     if [ "$ARCH" == "armv7l" ] || [ "$ARCH" == "armhf" ]; then         apk add --no-cache            bash            tzdata            python3            py3-pip            git            mosquitto-clients                    && git clone -b v2 https://github.com/andrea-mattioli/bticino_X8000_rest_api.git         && mv bticino_X8000_rest_api/* /hassio_bticino_smarter/         && rm -rf bticino_X8000_rest_api;     else         apk add --no-cache            bash            tzdata            python3            py3-pip            git            mosquitto-clients            chromium            chromium-chromedriver                    && git clone -b v2 https://github.com/andrea-mattioli/bticino_X8000_rest_api.git         && mv bticino_X8000_rest_api/* /hassio_bticino_smarter/         && rm -rf bticino_X8000_rest_api;     fi'


 ---> Running in 220315e4991f

+ uname -m

+ ARCH=armv7l
+ '[' armv7l '==' armv7l ]
+ apk add --no-cache bash tzdata python3 py3-pip git mosquitto-clients

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/armv7/APKINDEX.tar.gz

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)

fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/armv7/APKINDEX.tar.gz

WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)

ERROR: unable to select packages:

  git (no such package):
    required by: world[git]
  mosquitto-clients (no such package):
    required by: world[mosquitto-clients]
  py3-pip (no such package):
    required by: world[py3-pip]
  python3 (no such package):
    required by: world[python3]

Removing intermediate container 220315e4991f

```

**Comment by andrea-mattioli** [comment]
Try to rebuild the addon it doesn't reached repository during installation.

**Comment by gpanni77** [comment]
It is not possible, before I had the version "Bticino X8000" installed and removed it.
Now I am trying to install the version "Bticino X8000 v2" but I get the error I reported.
I tried to restart several times raspberry, docker, core, supervisor but I have not solved.

Unlike before when it was installed, I don't have the REBUILD button at the bottom right, just the INSTALL button at the bottom left.
It gives me the same error even if I try to install the older version "Bticino X8000" (not the "v2" version).

![BTicino](https://user-images.githubusercontent.com/57314917/115199004-fd789500-a0f2-11eb-9a92-42ee597362e4.JPG)

**Comment by andrea-mattioli** [comment]
Bticino X8000 is deprecated, use only the v2.
remove the old and reinstall the newest v2, you must change your app config and remove 5588 nat from your router.

**Comment by gpanni77** [comment]
Maybe I did not say it clear enough.

I have removed the old version and am trying to install the new one.
I am trying to install the version "Bticino X8000 **v2**" but I get the error I reported.
When I press install in the image I posted above, the errors I reported appear in the log.

**Comment by andrea-mattioli** [comment]
ok, i said you the error appear because the addon doesn't reached repository during installation, maybe you have a routing problem.

**Comment by gpanni77** [comment]
I tried running the command 
`apk add --no-cache bash tzdata python3 py3-pip git mosquitto-clients`
in an SSH session.
It works without problems.
Could the problem be docker related?

![BTicino](https://user-images.githubusercontent.com/57314917/115206724-2d2b9b00-a0fb-11eb-8bf4-5e512962bf73.JPG)

**Comment by andrea-mattioli** [comment]
I've Ubuntu with docker and it works fine, docker version:
```
root@ubuntu:~# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40 
```
Inside git repo there is a "docker file" try to build manually the addon to test docker  build process (there is not addon issue).
Linux Alpine image it's out of scope of my addon!

**Comment by gpanni77** [comment]
Ciao Andrea,
to fix I had to change, in the file Dockerfile, `FROM $BUILD_FROM` to `FROM hassioaddons/base-armv7:8.0.6`
It is definitely my specific problem, I just have to understand why it happens.
I think that you can close the issue.

Thank's for your job

**Comment by andrea-mattioli** [comment]
ok thanks for your feed
