### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by r0b3rt74** [andrea-mattioli/mattiols_hassio_repository#27]
Hi Andrea ,

today I updated the Smarther firmware to v1.1.102
Since the update I cannot connect to the app legrand anymore. I try to rebuild, re-start the add on, everything, but unfortunately without success. Could you please check what’s wrong here? Thank you very much

## System Health

version | core-2021.4.6
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.83-v8
arch | aarch64
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 5000
Installed Version | 1.12.1
Stage | running
Available Repositories | 842
Installed Repositories | 18

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.0
docker_version | 19.03.15
disk_total | 54.3 GB
disk_used | 8.7 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), File editor (5.3.0), deCONZ (6.8.0), Duck DNS (1.12.5), Mosquitto broker (5.1.1), ESPHome (1.16.2), Bticino X8000 v2 (2.6), Mattiols Reverse Proxy (0.2)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 15
views | 9
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

**Comment by andrea-mattioli** [comment]
Check if accidentally you removed third part access, the firmware update doesn't change api calls.

Regards

**Comment by r0b3rt74** [comment]
Since yesterday evening it works again. It looks like it was a server issue at legrand side. I did not change anything in the configuration. Thanks for the support!

**Comment by andrea-mattioli** [comment]
Great!
