### ISSUE TITLE
parser error

### ISSUE THREAD

**Issue by MAurOsX** [andrea-mattioli/mattiols_hassio_repository#3]
Hi Andrea, I've installed your integration but I end up with this parser error in log:

> File` "/usr/lib/python3.8/site-packages/yaml/parser.py", line 369, in parse_node
 raise ParserError("while parsing a %s node" % node, start_mark,
yaml.parser.ParserError: while parsing a block node
expected the node content, but found ']'
  in "config/config.yml", line 3, column 20

that refers to the first character of my client secret, that starts with ‘]’

'' client_secret: ']nX4c....' ''

..maybe because this character is misinterpreted?

**Comment by andrea-mattioli** [comment]
Hi Mauro,
please try to update to the last add-on version 0.3 and check if it works.
NB. you must click on rebuild after add-on update

**Comment by MAurOsX** [comment]
Hi Andrea, now it works! I also found out that was even working by adding double prefix like:

client_secret: ‘’’]nX4...’’’

But.. Now I’m still stuck at this point



 
It won’t go on and I get only this blank page



What could be wrong now?? 🤔

**Comment by MAurOsX** [comment]
![7216A503-BC67-4D65-80B7-C277AC8715FC](https://user-images.githubusercontent.com/63123682/81432496-4e51e080-9163-11ea-80d6-5fdec6076e0f.png)
![64AB043B-F54E-401D-A176-6C0B43E978EA](https://user-images.githubusercontent.com/63123682/81432507-54e05800-9163-11ea-8bf7-06a4b39a1c3a.png)

**Comment by andrea-mattioli** [comment]
I think you Have a wrong configuration on legrand app because I don’t see the port in the return url. Or if you use a reverse proxy you don’t have a true proxypass

**Comment by MAurOsX** [comment]
solved!
I actually had a config error on Nginx (just a trivial typo..) , now it works great
tnx!

**Comment by andrea-mattioli** [comment]
ok thanks for feed

**Comment by yashijoe** [comment]
> solved!
> I actually had a config error on Nginx (just a trivial typo..) , now it works great
> tnx!

Can you paste your Nginx configuration?
Thanks!
