### ISSUE TITLE
nessun aggiornamento da giorni

### ISSUE THREAD

**Issue by tabs78** [andrea-mattioli/mattiols_hassio_repository#31]
ciao, senza aver cambiato nulla ho notato che da giorni non aggiorna più le temperature automaticamente mentre manualmente va tutto

**Comment by andrea-mattioli** [comment]
Prova a cancellare il packages fare il rebuild dell'addon e rifare il get code.
A me funziona e non ho avuto altre segnalazioni

**Comment by tabs78** [comment]
provato ma non sembra risolvere.
nel log dell'addon non sembrano arrivare i post

mentre nel log dell'addon reverse proxy trovo cose così:

137.117.138.96 - - [10/Jul/2021:14:39:21 +0200] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 400 16 "-" "-"
2021/07/10 14:39:22 [info] 231#231: *5 client 137.117.138.96 closed keepalive connection

**Comment by andrea-mattioli** [comment]
Prova ad aggiungere sul configuration.yaml
'''
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
'''

**Comment by tabs78** [comment]
Ho visto la guida per quella stringa ma dice di mettere l'indirizzo del proprio proxy.

**Comment by andrea-mattioli** [comment]
Con il codice che ti ho mandato accetti tutta la rete dei container 

Inviato da iPhone

**Comment by majorhector** [comment]
Ho anche io questo problema. Da settimane non mi aggiorna più la temperatura finchè non gli do io un comando. Ho provato a cancellare tutto e fatto il rebuild ma niente. Ho seguito la guida alla lettera. Funziona tutto ma non mi aggiorna i dati (temperatura impostata, temperatura attuale, ecc....)
