### ISSUE TITLE
Modifiche parametri sicurezza

### ISSUE THREAD

**Issue by satomma** [andrea-mattioli/mattiols_hassio_repository#32]
Ho ricevuto questa comunicazione da bticino
```
Gentile cliente,

con l'obiettivo di mantenere sempre un alto livello di sicurezza nelle nostre applicazioni
le comunichiamo che a breve elimineremo alcuni protocolli di transazione che non sono 
ritenuti più conformi agli standard internazionali dalle seguenti app Thermostat, Bticino Power ON, 
Door Entry Classe300X, Door Entry for Hometouch e MyHome_Web.
```

Potrebbe avere impatti sull'integrazione?

**Comment by andrea-mattioli** [comment]
no c'è scritto: "This changes will affect you only if you are still running those app with a Android 5.0 or a an even older version, we suggest, in this case if possible, and update of the operative system on the device."
