### ISSUE TITLE
passaggio v1 a v2

### ISSUE THREAD

**Issue by ripperhack** [andrea-mattioli/mattiols_hassio_repository#33]
ciao Andrea, prima di tutto ottimo lavoro.
Avevo installato il tuo addon v1 che funzionava e sono passato alla v2. Tra le varie prove ho rimosso il packages creato dalla v1, installato la v2, provato a fare il rebuild della v2 ma niente il package non si ricrea. Cosa devo provare? grazie
![immagine_2021-08-05_134554](https://user-images.githubusercontent.com/86116662/128344762-cd5e6160-f18f-4c90-8460-00c5b587f051.png)

**Comment by ripperhack** [comment]
![immagine_2021-08-05_134706](https://user-images.githubusercontent.com/86116662/128344893-19cde07e-4671-4835-abdf-fd648415e205.png)
configuration.yaml corretto

**Comment by ripperhack** [comment]
e quando vado a fare "apri l'interfaccia web" mi punta correttamente a https://xxxxxxxx.duckdns.org:5588/ ma poi non si apre

**Comment by andrea-mattioli** [comment]
Leggi il readme, è cambiato tutto, non devi utilizzare la  porta con l'ip pubblico ma quello in locale, devi aggiornare l'app sul sito legrand, per gestire duck con http su indirizzi locali installati l'addon del proxy.
praticamente è cambiato tutto dalla v1 alla v2.

**Comment by ripperhack** [comment]
si grazie, ho già aggiornato l'app su lengrand e mi è stata già approvata, il problema è che non si ricrea il packages facendo il rebuild. Immagino che sia ancora necessario o sbaglio?

**Comment by andrea-mattioli** [comment]
il package lo scarichi dall'app quando vai sulla porta 5588, se non ti parte devi avere qualche altro problema
https://github.com/andrea-mattioli/mattiols_hassio_repository/tree/master/bticino_X8000_v2#4-home-assistant-integration

**Comment by andrea-mattioli** [comment]
puoi fornire un feedback oppure chiudere la issue?
Altrimenti si chiuderà in automatico tra 2gg per inattività

**Comment by ripperhack** [comment]
chiudo, il problema era la presenza della v1. Da installazione pulita funziona perfettamente
