### ISSUE TITLE
problema certificato ssl reverse proxy

### ISSUE THREAD

**Issue by runnerluca87** [andrea-mattioli/mattiols_hassio_repository#34]
Buongiorno,
ho un problema con il certificato ssl sul reverse proxy con duckdns, da ieri risulta scaduto.
il log mi restituisce questo errore
2021/08/18 10:19:37 [info] 231#231: *1 SSL_read() failed (SSL: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired:SSL alert number 45) while waiting for request, client: x.x.x.x, server: 0.0.0.0:443

ho provato anche a re-installare e con il rebuild ma il problema rimane.
c'è qualche ulteriore operazione che posso fare?

grazie in anticipo

**Comment by andrea-mattioli** [comment]
quando parte l'addon fa il check se il certificato è scaduto, puoi riavviare l'addon e farmi vedere i log dello start?

**Comment by runnerluca87** [comment]
ho appena risolto il problema cancellando il vecchio certificato e all'attivazione l'addon ha forzato la rigenerazione di un nuovo certificato, purtroppo non ho più il log di avvio.
Cmq mi ricordo che all'avvio veniva effettuato solo un controllo sulla presenza del certificato dentro la cartella (esito positivo) e non era presente alcun errore sull'avvio.
Il warning sul log veniva fuori quando provavo a collegarmi dall'esterno in https e sul log veniva riportato l'errore del "certificate expired" .

**Comment by andrea-mattioli** [comment]
si quello è corretto, volevo capire il motivo per il quale non ti aggiornava quello vecchio!

**Comment by runnerluca87** [comment]
dal log che usciva non erano presenti errori, cmq questo certificato nuovo esce a novembre, in caso ci riaggiorniamo fra 2 mesi :) :) 

Grazie mille del supporto e del lavoro!

**Comment by andrea-mattioli** [comment]
di nulla! buona giornata
