### ISSUE TITLE
Thermostat v1 Errore 7 hassio

### ISSUE THREAD

**Issue by danisk89** [andrea-mattioli/mattiols_hassio_repository#37]
Ciao Andrea, purtroppo durante un installazione su un docker con hassio mi è capitato questo errore, cosa potrebbe essere? 

The command '/bin/ash -o pipefail -c apk add -no-cache bash tzdata python3 py3-pip mosquitto-clients openssl ngix certbot certbot-ngix' returned a non-zero code: 7

Grazie, 
Ciao

**Comment by danisk89** [comment]
Avviando il docker mi da questo errore
28: sc.sh: --name: not found

Il giorno ven 27 ago 2021 alle ore 16:31 Daniel Scaini ***@***.***>
ha scritto:

**Comment by andrea-mattioli** [comment]
Guarda dipende dalla versione di docker che usi, il --name ti crea un common name del container.
se non ti funziona puoi toglierlo, quelle sono le variabili che devi passare al container, e lo share del fs /config di home assistant.
se ti serve qualche cosa nello specifico consulta la documentazione di docker

**Comment by danisk89** [comment]
Ok, grazie mille

Il lun 30 ago 2021, 10:45 andrea-mattioli ***@***.***> ha
scritto:

**Comment by danisk89** [comment]
Unable to find image 'amattioli2/homeassistant_addon_bticino_x_8000:armv7l'
locally
docker: Error response from daemon: pull access denied for
amattioli2/homeassistant_addon_bticino_x_8000, repository does not exist or
may require 'docker login': denied: requested access to the resource is
denied.

Il giorno lun 30 ago 2021 alle ore 10:49 Daniel Scaini ***@***.***>
ha scritto:

**Comment by andrea-mattioli** [comment]
è :armv7 l'arch non 7l fissalo a mano

**Comment by danisk89** [comment]
No purtroppo stesso errore, il path è corretto?
Qui la parte finale del processo
5588:5588 -v 'EX /config':/config --name ha_bticino_x_8000
amattioli2/homeassistant_addon_bticino_x_8000:armv7

Il giorno mar 31 ago 2021 alle ore 16:28 andrea-mattioli <
***@***.***> ha scritto:

**Comment by andrea-mattioli** [comment]
funziona...
stai sbagliando qualcosa
```
ubuntu@ubuntu:~$ docker pull amattioli2/homeassitant_addon_bticino_x_8000:armv7
armv7: Pulling from amattioli2/homeassitant_addon_bticino_x_8000
4ee0caa23b36: Pull complete 
06e1c75015b3: Pull complete 
f9a4e17c399b: Pull complete 
d3ecd30fef7c: Pull complete 
27b4fea4af1f: Pull complete 
89477354e1c8: Pull complete 
Digest: sha256:08dc9c88d057b599161177900d4d3afb5b3e32de27ab568aff93fe7ef952dea7
Status: Downloaded newer image for amattioli2/homeassitant_addon_bticino_x_8000:armv7
docker.io/amattioli2/homeassitant_addon_bticino_x_8000:armv7
```

**Comment by danisk89** [comment]
Eh no, il path da cui parti tu è

docker pull amattioli2/homeassitant_addon_bticino_x_8000:armv7

Il mio ha una s in più formando homeassistant

Però va benissimo ho scaricato e all'avvio mi da questo
(in allegato)

Il mar 31 ago 2021, 17:27 andrea-mattioli ***@***.***> ha
scritto:
