### ISSUE TITLE
Problemi di connessione

### ISSUE THREAD

**Issue by djgragra** [andrea-mattioli/mattiols_hassio_repository#38]
Da un paio di giorni non riesco più ad accedere ad HA da xxx.duckdns.org da app o computer quando sono connesso alla rete di casa. Se invece ad es. sono in ufficio accedo tranquillamente da app e PC.
Ho una linea Sky wifi e fin'ora non ha mai dato questo problema.

**Comment by andrea-mattioli** [comment]
Se ti riferisci all'addon del reverse proxy, nella rete locale devi usare l'indirizzo ip locale 192.168.1.x

**Comment by djgragra** [comment]
È già così. Se non sono collegato alla mia rete funziona perfettamente. Ho contattato il servizio clienti Sky wifi per sapere se per caso hanno bannato il mio indirizzo xxx.dukdns.org, mi faranno sapere🤕

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 3 set 2021, 21:14 +0200, andrea-mattioli ***@***.***>, ha scritto:

**Comment by andrea-mattioli** [comment]
Non mi sono spiegato probabilmente...
Da dentro casa non devi andare sul dominio duckdns ma su l'indirizzo locale:8143 
Così devi configurare l'app indirizzo per rete interna e duck per reti esterne

**Comment by djgragra** [comment]
Ma fino a 3gg fa funzionava anche l’url esterno. Te lo assicuro.

Graziano Melzi

Please consider the environment before printing this e-mail notice
Il 3 set 2021, 21:22 +0200, andrea-mattioli ***@***.***>, ha scritto:

**Comment by andrea-mattioli** [comment]
Non ha senso utilizzare l'ip pubblico dalla rete locale.
È stato fatto appositamente il reverse proxy...
