### ISSUE TITLE
Refresh missing

### ISSUE THREAD

**Issue by davliojk83** [andrea-mattioli/mattiols_hassio_repository#42]
Hi, 
my card don't refresh data automatic.
The data change only if I open http://....:5588/info address.
Could you please help me?

**Comment by andrea-mattioli** [comment]
1. Check the c2csubscription, inside the app http://192.168.1.x:5588/c2c_subscription.
2. Check the addon's logs, you must receive POST from legrand.

**Comment by Prismakill** [comment]
Hi!
It happens the same as @davliojk83 to me.
I've checked the c2c_subscription and I can see my subscription with the endpoint url pointing my hassio machine, but can't see any "POST" from legrand on the logs.
Could be something about http and https?, due I can't acces my hassio trough https.
Thank you!!

**Comment by Prismakill** [comment]
Sorry for oppening a new issue.
Want to add that enabling httpS, solved the problem, now it refresh itselfs! 
Thank you!!
