### ISSUE TITLE
Info compatibilità 

### ISSUE THREAD

**Issue by GabrieleMandalari** [andrea-mattioli/mattiols_hassio_repository#44]
Ciao Andrea, che tu sappia il tuo addon è compatibile anche con la versione SXW8002?

**Comment by andrea-mattioli** [comment]
No solo con x8000

Inviato da iPhone

**Comment by GabrieleMandalari** [comment]
Perché sulla carta dovrebbero essere molto simili i due modelli. Proverò e ti aggiorno

**Comment by andrea-mattioli** [comment]
Non sono simili nemmeno per niente…
Uno ha il firmware proprietario bticino/legrand l’altro ha il firmware netatmo

Inviato da iPhone
