### ISSUE TITLE
Stop working after 2 days

### ISSUE THREAD

**Issue by onofalt** [andrea-mattioli/mattiols_hassio_repository#47]
Dopo due giorni l'addon smette di funzionare (non è presente nulla nei log) ed al riavvio perde l'associazione con legrand e devo rifare l'autorize sul sito prima che rifunzioni.

**Comment by onofalt** [comment]
log extraction

192.168.0.5 - - [28/Jan/2022 19:29:43] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 19:29:46] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 20:10:46] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
Job "f_refresh_token (trigger: interval[0:50:00], next run at: 2022-01-28 21:07:03 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/hassio_bticino_smarter/bticino.py", line 273, in f_refresh_token
    if not check_empty_item("refresh_token"):
  File "/hassio_bticino_smarter/bticino.py", line 83, in check_empty_item
    json_object=get_json()
  File "/hassio_bticino_smarter/bticino.py", line 124, in get_json
    a_file = open(api_config_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'config/smarter.json'
192.168.0.5 - - [28/Jan/2022 20:29:37] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 20:35:00] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 20:55:19] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
Job "f_refresh_token (trigger: interval[0:50:00], next run at: 2022-01-28 21:57:03 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/hassio_bticino_smarter/bticino.py", line 273, in f_refresh_token
    if not check_empty_item("refresh_token"):
  File "/hassio_bticino_smarter/bticino.py", line 83, in check_empty_item
    json_object=get_json()
  File "/hassio_bticino_smarter/bticino.py", line 124, in get_json
    a_file = open(api_config_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'config/smarter.json'
192.168.0.5 - - [28/Jan/2022 21:19:49] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 21:20:45] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 21:50:01] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 21:51:48] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
192.168.0.5 - - [28/Jan/2022 21:51:49] "POST /api/webhook/mattiols_x_8000 HTTP/1.1" 404 -
Job "f_refresh_token (trigger: interval[0:50:00], next run at: 2022-01-28 22:47:03 CET)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/hassio_bticino_smarter/bticino.py", line 273, in f_refresh_token
    if not check_empty_item("refresh_token"):
  File "/hassio_bticino_smarter/bticino.py", line 83, in check_empty_item
    json_object=get_json()
  File "/hassio_bticino_smarter/bticino.py", line 124, in get_json
    a_file = open(api_config_file, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'config/smarter.json'
192.168.0.149 - - [28/Jan/2022 22:17:16] "GET /rest HTTP/1.1" 401 -

**Comment by andrea-mattioli** [comment]
Hai cancellato la directory dentro config .smarter_bticino, poi non hai il packages che ti mette il webhook leggi la documentazione dei passi da fare per configurare l'addon.

**Comment by onofalt** [comment]
Andrea, ho letto la config, ho installato il package tramite HACS. In che senso "hai cancellato la directory .smarter_bticino"?  Io non ho cancellato nulla, Per tua informazione con la v1 funziona tutto senza questo problema, la v2 va poi dopo un paio di giorni si pianta con gli errori 404 dopo che va in crash il docker e viene automaticamente riavviato

**Comment by andrea-mattioli** [comment]
la v1 rispetto alla v2 ha una configurazione totalmente diversa, quindi non puoi fare switch da una all'altra senza cambiare configurazione sul router di casa e sull'app del portale legrand.
Non ho altre evidenze di crash del container, dai log che mi hai mandato l'applicazione non riesce a leggere i file che usa sotto config/.smarter_bticino.
Cancella tutto rimuovi packages e directory dentro config/.smarter_bticino e segui bene la documentazione.
Per me stai mandando i webhook non su HA ma sull'applicazione...
