### ISSUE TITLE
Help needed, Internal Server Error.

### ISSUE THREAD

**Issue by becauseht** [andrea-mattioli/mattiols_hassio_repository#48]
Hi Andrea, i've been using your add-on since 2 years, but now i have problem cause whenever i try to make the procedure to get a code the callback fail with this error:
"
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
"
Following you can find my add-on log, do you have any suggestion? I've tryed also unistall and reinstall the add-on but the same error came up again

s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:06:43] INFO: Smarter file already exist and contain some data.
[12:06:43] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.30.33.5:5588/ (Press CTRL+C to quit)
87.2.149.30 - - [29/Jan/2022 12:06:50] "GET / HTTP/1.1" 200 -
[2022-01-29 12:06:57,745] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 332, in get_topology
    Null,programs=get_programs_name(access_token, plant, topologyid)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/hassio_bticino_smarter/bticino.py", line 745, in callback
    chronothermostats=get_topology(access_token,my_plants)
  File "/hassio_bticino_smarter/bticino.py", line 336, in get_topology
print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'TypeError' object has no attribute 'errno'

**Comment by andrea-mattioli** [comment]
Check if you have "third party access" is enable from the official bticino smarter app (mobile)
This error catch when you developer account can't access on your home plant and topology, make all checks on legrand app.
Try also to get your thermostat info by the official legrand's api: 
https://portal.developer.legrand.com/docs/trought official legrand api: 
https://portal.developer.legrand.com/docs/services/smartherV2/operations/Plants
https://portal.developer.legrand.com/docs/services/smartherV2/operations/Topology

**Comment by becauseht** [comment]
Ciao Andrea, ti rispondo in italiano così è più comodo (spero non sia un problema), ho verificato attraverso l'app e l'accesso terze parti è ok, ho anche provato tramite il portale developer sia plant che topology e entrambi rispondono correttamente, lato HA invece nulla, una volta che devo accettare i permessi clicco su "accetta" e subito dopo mi appare la pagina con internal server error, la cosa molto strana è che ha smesso di funzionare solo da qualche giorno perchè fino a pochi giorni fa tutto era perfetto, ho provato a ripristinare anche un vecchio full backup ma nulla l'errore rimane, hai qualche altro suggerimento?
![immagine](https://user-images.githubusercontent.com/9611125/151858678-73a9c7ef-38c6-4c4b-ac42-9276bcc516d9.png)

**Comment by andrea-mattioli** [comment]
ma controlla che sia tutto corretto lato utenze key etc etc, altrimenti come estrema ratio, puoi provare a rimuovere la directory config/.bticino_smarter e fare il rebuild dell'addon

**Comment by mirkoarere** [comment]
Ciao Andrea, ho installato e configurato il plugin ma quando vado a cliccare sul pulsante "accetta" dopo aver cliccato su GET YOUR CODE per consentire l'accesso all'app, mi appare il messaggio:

**Internal Server Error**
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.


per controllare lo smarther2 io uso **App Home + Control**


grazie in anticipo

**Comment by andrea-mattioli** [comment]
**Quello smarter NON è supportato l'addon è solo per X8000**
