### ISSUE TITLE
Errore Get Your Code

### ISSUE THREAD

**Issue by demaiopacido** [andrea-mattioli/mattiols_hassio_repository#49]
Buongiorno
ho impostato come reply url https://192.168.1.175:5588 sia su Legrand che su HAip ma continuo a ricevere la seguente risposta quando attivo get your code:
error": "invalid_request",
  "error_description": "The reply url host https doesn't match with the ones configured on the application"
dove sbaglio?

Questo il log del registro
Bticino X8000 v2
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:17:04] INFO: Smarter file already exist and contain some data.
[12:17:04] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://172.30.33.5:5588/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/hassio_bticino_smarter/mqtt.py", line 40, in <module>
    client.connect(mqtt_broker, mqtt_port, 60)
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "/usr/lib/python3.9/site-packages/paho/mqtt/client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
192.168.1.99 - - [08/Feb/2022 12:17:13] "GET / HTTP/1.1" 200 -

**Comment by andrea-mattioli** [comment]
Guarda, con 2 pezzi di log non ti posso essere di aiuto, la configurazione è descritta sulla documentazione e online ci sono un sacco di guide.
Cancella la vecchia app, ne fai una nuova su legrand e segui passo passo la guida.
Ricordati una volta che avrai risolto di rimuovere le c2c subscription errate che si sono generate con questi tentativi di configurazione sbagliata.

#CLOSED "not a bug, user misconfiguration"
