### ISSUE TITLE
User addon without Internet access

### ISSUE THREAD

**Issue by gobbe87** [andrea-mattioli/mattiols_hassio_repository#5]
Hi Andrea,
the internet pubblication for Hassio is required for use this addon?

Legrand need to communicate with hassio?

Thank you, regards
Alberto

**Comment by andrea-mattioli** [comment]
Hi Alberto, unfortunately Legrand need to communicate with hassio and vice versa.
Regards
Andrea

**Comment by gobbe87** [comment]
Thank you, I install the addon and i read better the doc and I publish to internet only the addon.
It works! thank you very much for you work!

Regards, Alberto
