### ISSUE TITLE
Devo aprire entrambe le porte sul router? Se apro solo la 443 non rinnova il certificato?

### ISSUE THREAD

**Issue by tabs78** [andrea-mattioli/mattiols_hassio_repository#50]

**Comment by andrea-mattioli** [comment]
a quale addon ti riferisci?

**Comment by tabs78** [comment]
Reverse proxy. Mi chiedevo se basti lanporta 443 oppure senza la 80 non rinnova il certificato

**Comment by andrea-mattioli** [comment]
Per il rinnovo serve la 80:
https://community.letsencrypt.org/t/is-port-80-required-for-renewals/121432/4

Per l'accesso da remoto su una porta diversa da 443 devi fare un nat sul router e fai la redirezione da una porta "X" alla 443 di HA.
