### ISSUE TITLE
Suggerimento su problema...

### ISSUE THREAD

**Issue by DarioPalmisan** [andrea-mattioli/mattiols_hassio_repository#52]
Buongiorno,
ho provato in tutti i modi per cercare di farla funzionare, ma senza successo.
Non so se qualcuno (magari lo sviluppatore) mi puo' dare una indicazione riguardo alla diagnostica di seguito riportata (ho anche allegato il log).
Grazie in anticipo

 File "/hassio_bticino_smarter/bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'

[Diags.txt](https://github.com/andrea-mattioli/mattiols_hassio_repository/files/8388209/Diags.txt)

**Comment by andrea-mattioli** [comment]
Su quale modello di smarter stai provando?
l'addon supporta solo X8000 (smarther 1) quello non netatmo per capirci.
