### ISSUE TITLE
addons stop working

### ISSUE THREAD

**Issue by parabag** [andrea-mattioli/mattiols_hassio_repository#53]
Andrea,
after a coupleof months of this addons working successfully I experienced a total stop of the webhooks for more than 24h(not a Legrand problem), cancelled my bticino_smarther folder andtryed to re-built the addon. Now I am not able any more to access neither the page of th C2C subscription, neither get code, neither rhrrmostat info. I paste below the log. Thanks for your advise.

Luca

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:38:28] INFO: Init Smarter file ...
[15:38:28] INFO: 64bit Version detected
[15:38:28] INFO: Setup config file...
 * Serving Flask app 'bticino' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5588
 * Running on http://172.30.33.2:5588 (Press CTRL+C to quit)
[15:38:31] INFO: Trying autologin to Legrand...
/hassio_bticino_smarter/login.py:40: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  username = driver.find_element_by_xpath("//input[@id='logonIdentifier']");
/hassio_bticino_smarter/login.py:47: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  password = driver.find_element_by_xpath("//input[@id='password']");
/hassio_bticino_smarter/login.py:31: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  accept_b=driver.find_element_by_xpath("//input[@class='btn btn-primary pull-left']");
[2022-04-14 15:38:51,483] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 332, in get_topology
    Null,programs=get_programs_name(access_token, plant, topologyid)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/hassio_bticino_smarter/bticino.py", line 745, in callback
    chronothermostats=get_topology(access_token,my_plants)
  File "/hassio_bticino_smarter/bticino.py", line 336, in get_topology
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'TypeError' object has no attribute 'errno'
172.30.32.1 - - [14/Apr/2022 15:38:51] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..amd-ZkOFy2BnzS5X.9k7YUYg5A8lyFfIfjZSAHG8qDZeC4hH_Pgy7p0poXTPresLS8Vk0k3B9Njn4QOVCvXu5oLpPJGMP8DKTXLjS2cix0L_8h2mRDO9DFFghtgLLWAVL-h9LaqevnQFh7o0VKxyOcdkq55vwQ8zQR-cHufwW8-_bPkKkONgYDDHiu6cnIfGuqKTGQ0H2cxoAhDAJWGQcZ6qq3z320EnIUObqzEicNeaOaWHP1SbKW_XVlpgUtwsSt4n_tcQujuoGSt4JKOVnKqnRJXkA9XFEWWTpoJGX_smj4kaJICZfjA60EM_CGlGedXFmyCmORUMcqvUPIzU_JfZfT78-bhbggs2PKQ5vZ26PqO3hnHEjpzfCbbJ2QWeScvy12tzPr6oWWAQZAthF84OEhIx5KrPGvYjCt3d2dcJ1m5wmDLZDJypcwHZRHXNuskVsOJQ7h_fiHKvJKhpxN_noHtJ3JF4bXLo5l2Lc5L2bdGmdqtDeckK20V3aDW9FU13od_yWVJnHoNV6uCxxXSDprHOmF_aES3QW3T1p4SKaK4GEFG9kHhwA8Ma7aFzkJLQLzdIO2c06PXNa0QSFQpOMQGPU9LtdEOZ7MwCnF9AbNXI31g1AHLhLl9Vb4hSDbti_aYwU_2Qyo8hqa4wK1CsR_v_TC5efmiU1CO7EC8SF2z86z7PVlyf_VWMJBil3XBFrkJuFRHlkAcFsJ28GjoS9G1uzjHFzLX-o6CJxzlRNi8WrYFIG7jHmLfBZLNuw2BINdmJ8IXyE-QjwYCzEHj84AgvfXm8-E510YzE214807bRitTEjicJWTG_MhUNtSGUaQbtBnSm_c2olpWMScQHBVOmgMQEBq-eEWReuuw3Rmc_1c2QXh_4XxtdpYqdcN7sKmlg.3E387CkBpp01vmySH2mlEA&state=axUHlyZWEVFRJSraGOKnr9QmAoTkjHDz HTTP/1.1" 500 -
Successfully login to Legrand
[15:38:51] INFO: Succesfully autologin to Legrand
93.71.88.16 - - [14/Apr/2022 15:39:03] "GET / HTTP/1.1" 200 -
[2022-04-14 15:39:11,053] ERROR in app: Exception on /c2c_subscription [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 210, in get_c2c_subscription
    plantId=(j['plantId'])
TypeError: string indices must be integers
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/hassio_bticino_smarter/bticino.py", line 215, in get_c2c_subscription
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'TypeError' object has no attribute 'errno'
93.71.88.16 - - [14/Apr/2022 15:39:11] "GET /c2c_subscription HTTP/1.1" 500 -

**Comment by andrea-mattioli** [comment]
Did you tried to click on get your code?
could you post the content of files present inside .bticino_smarter?
I tried to rebuild my addon and i don't have your issue with the deprecated function warning.
Do you use HA OS or debian/ubuntu with docker?

**Comment by parabag** [comment]
ciao Andrea,
Inside bticino_smarther there is one file named smarther.json with this
content:
{"api_requirements": {"code": "", "access_token": "", "refresh_token": "",
"chronothermostats": ""}}

I am running HA OS 2022-4-1

thx

L

Il giorno ven 15 apr 2022 alle ore 13:07 Andrea Mattioli <
***@***.***> ha scritto:

**Comment by andrea-mattioli** [comment]
OK, but the button "get your code" works?

**Comment by parabag** [comment]
Andrea,
"get your code" was not working... up until 2 days ago... now everything is
working fine again...
Legrand told me that the webhook end point was not responding so not able
to send them and they (the webhooks) are automatically stopped for
sometimes.
Could it be possible Andrea? and if yes how could I avoid it?

grazie

Luca

Il giorno mar 19 apr 2022 alle ore 18:01 Andrea Mattioli <
***@***.***> ha scritto:

**Comment by andrea-mattioli** [comment]
Hi Luca, 
the addon's code is immutable unlike Legrand's services! Unfortunately i can't avoid Legrand's services issue, i must use their API to manage the thermostats.
