### ISSUE TITLE
versione 0.3 non funziona

### ISSUE THREAD

**Issue by pierclaudio** [andrea-mattioli/mattiols_hassio_repository#55]
Salve, appena aggiornato alla versione 0.3 ma restitutisce il seguente errore:
ERROR: Unknown HTTP error occured

**Comment by andrea-mattioli** [comment]
Prova la 0.4, purtroppo hanno cambiato delle cose con l'ultimo aggiornamento di HA, questo è un workaround appena ho tempo cerco di fare un fix sui nuovi standard.

**Comment by rul3zz** [comment]
Confermo stesso problema 2022.5.5

**Comment by yashijoe** [comment]
Ciao, il problema è lo stesso che mi genera questo messaggio sul log de X8000v2?

s6-overlay-suexec: fatal: can only run as pid 1

grazie

**Comment by andrea-mattioli** [comment]
mi confermate che la la 0.4 del proxy vi funziona?

**Comment by rul3zz** [comment]
> mi confermate che la la 0.4 del proxy vi funziona?

si funziona

**Comment by yashijoe** [comment]
> s6-overlay-suexec: fatal: can only run as pid 1

Problema risolto con l'update di oggi
Grazie
