### ISSUE TITLE
Sola lettura

### ISSUE THREAD

**Issue by yashijoe** [andrea-mattioli/mattiols_hassio_repository#56]
Ciao, sto usando la versione 2.7.
Se modifico la temperatura, dopo un paio di sec, questa torna sul valore impostato nell’app ufficiale bticino.
In sostanza riesco a leggere tutti i parametri correttamente, ma se li modifico poco dopo tornano a quelli definiti nell’app
Grazie

**Comment by andrea-mattioli** [comment]
prova a rifare get code dalla pagina dell'app, se non funziona cancella la directory .bticino_smarter e rifai get code

**Comment by yashijoe** [comment]
> prova a rifare get code dalla pagina dell'app, se non funziona cancella la directory .bticino_smarter e rifai get code

Ho provato quanto hai scritto.
Ho anche provato a rimuovere tutto: addon, cartella .bticino_smarte e anche il package. Reinstallato tutto.

Stesso problema
Ho anche controllato di aver il permesso write sulla voce comfort
Grazie

**Comment by yashijoe** [comment]
> Non so che dirti, io ho provato a modificare parametri, cambiare scheduler o spegnere da HA il termostato e funziona tutto correttammente. puoi provare a metterti in ascolto sull'mqtt e vedere cosa passa quando dai i comandi: da terminal:
> 
> ```
> mosquitto_sub -h "tuo ip 192.168.1.X" -u "tuo utente mqtt" -P "tua pass mqtt" -v -t "/bticino/#"
> ```

Ciao Andrea, mi ritorna correttamente quanto modificato da lovelace, tipo:
/bticino/xxxxxxxxxxxx/cmd 8.0
/bticino/xxxxxxxxxxxx/cmd heat

Solo che non succede nulla e allo status successivo risulta tutto invariato
Mi sfugge come possa leggere e non scrivere

**Comment by yashijoe** [comment]
Ciao Andrea, ho reinstallato mqtt e ora funziona.
Ti ringrazio

**Comment by andrea-mattioli** [comment]
ok ottimo!
