### ISSUE TITLE
Climate MQTT - nuova configurazione

### ISSUE THREAD

**Issue by yashijoe** [andrea-mattioli/mattiols_hassio_repository#57]
Ciao, è in programma un aggiornamento del pacchetto per adeguarsi alla nuova configurazione di climate sotto mqtt?

Riporto:
The configuration format of manual configured MQTT items has changed. The old format that places configurations under the climate platform key should no longer be used and is deprecated.

Fonte:
https://www.home-assistant.io/integrations/sensor.mqtt/#new_format

Ti ringrazio in anticipo per una risposta

**Comment by andrea-mattioli** [comment]
WIP

**Comment by ivanlouis87** [comment]
Ciao Andrea,
Intanto grazie per il tuo prezioso lavoro, davvero notevole!
Questa issue è per caso legata alla attuale impossibilità di installare? il metodo callback sembra andare in errore ad ogni utilizzo in fase di installazione. Eventualmente posso fornire stacktrace.
Grazie mille

**Comment by DjMayone** [comment]
> Ciao, è in programma un aggiornamento del pacchetto per adeguarsi alla nuova configurazione di climate sotto mqtt?
> 
> Riporto: The configuration format of manual configured MQTT items has changed. The old format that places configurations under the climate platform key should no longer be used and is deprecated.
> 
> Fonte: https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
> 
> Ti ringrazio in anticipo per una risposta

Ciao Andrea,
sarei interessato anche io rispetto al rilascio di una versione aggiornata; ho provato ad editare il file di configurazione ma non ci ho cavato un ragno dal buco.

**Comment by yashijoe** [comment]
Grazie per l'update!
Lo installo subito
