### ISSUE TITLE
Errore all'attivazione del server

### ISSUE THREAD

**Issue by fuzzybear62** [andrea-mattioli/mattiols_hassio_repository#58]
Ciao, 
da qualche giorno, senza nessuna modifica intercorsa, all'avviamento del server dell'add-on, ricevo questo log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[18:27:17] INFO: Smarter file already exist and contain some data.
[18:27:17] INFO: Setup config file...
 * Serving Flask app 'bticino'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5588
 * Running on http://172.30.33.3:5588
Press CTRL+C to quit
213.215.201.148 - - [17/Oct/2022 18:28:46] "GET / HTTP/1.1" 200 -
213.215.201.148 - - [17/Oct/2022 18:28:46] "GET /favicon.ico HTTP/1.1" 404 -
[2022-10-17 18:30:59,265] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 332, in get_topology
    Null,programs=get_programs_name(access_token, plant, topologyid)
TypeError: cannot unpack non-iterable NoneType object
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/hassio_bticino_smarter/bticino.py", line 745, in callback
    chronothermostats=get_topology(access_token,my_plants)
  File "/hassio_bticino_smarter/bticino.py", line 336, in get_topology
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'TypeError' object has no attribute 'errno'
213.215.201.148 - - [17/Oct/2022 18:30:59] "GET /callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..BI6oSDvjJmTYF-yO.GfzTCa1yttpXTUKgDqkBjDccql-3S5KcNPiC5QUHcSTuKL9rImjKmqSMk2Q5M0kPzzdoXkPAn2b9-KCFRlc7yPZeAlSkV3vzbMk3ZfJu2Z01JdI6kSuX1fHvI_YX7YwuKJTNTz2D_Bj4amxnVTatg4L_jD4lhsJzKPwb8Wxo3kVmbma3vWXKxItuYVC2hs-o8w059-XvY_TFDrS0ZQ5Ecbzmkfd-TPmxdOCFXFzDW9kLQJsJeij-NKoD_Ya8ljfMYUKSe0i-tvNZUlQyIl4DyBjS9WU820uifFbLkcWMEfWtdfawwoADWKDYyJ09zcuj45T_u7lSJWZ61jhwSumfaY5OXkFYSr-1bWZM6MjRRZGxFPIxCuKWhP9NNMP_7d4J0N9ftHP4ElrFfx2hp8qRKLm10AQLET-F1Xi9U6M1YKShD-NytlPQ5Xn7Jf-yyVpZJikkxU2GNOi7rFwyGIpdz_kklZ-fvWUdt6h-OvheOUOAikJ-17Psa2AHSx_YGvYAb5WDYXSuj7cWfHg8NN1fH7TDwp6gu5nCm_3AgWGGHn9SYIIbxQc5pXgdvqWFL0LkhEEUTmA1DN426AsH0Zo2WfFUpBVb19-1kPxvjd3MNhVCMiSwibkybVeWB6Hv8_vDG1hr2DkOp_8vMEVrgQLzQbADEbdt8Xj-OeSmKSxt8UBgkP8HmU0c8-yHUACpmr9t-otxd6eDaMBnzK25HRcOA48oFNR6mLn9x-1BGFty8g5bSJ7F0MPngADmqfVHCypvB3CRVJ3tiALqVaRM_FMNqJ_OygIKfwUnXtdNsI2x61gvJThduE7rEGJVebigz1YuirqVWq4qbYcmn-5aRObfMce2ztrKKw1EWD3isFxLdGzNpHVC.sHA0SIrBfBfHHM1ThVb6Nw&state=7EyMUKumpZnabs8Eqm70eJqLIRkOvETd HTTP/1.1" 500 -

Sto usando la distribuzione su Raspberry CM3+
Ho provato a fare rebuild, ma senza successo

 Home Assistant 2022.10.4 Supervisor 2022.10.0 Operating System 9.2 Frontend 20221010.0 - latest

**Comment by almico** [comment]
Mi sa che ho un problema molto simile. Cercando di eseguire il "Get your code", arrivo alla richiesta di accettare l'accesso, e poi il browser mi dice:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

Nel log dell'add-on trovo:

```
Press CTRL+C to quit
192.168.1.212 - - [25/Nov/2022 18:36:15] "GET / HTTP/1.1" 200 -
[2022-11-25 18:36:23,831] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "/hassio_bticino_smarter/bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/hassio_bticino_smarter/bticino.py", line 744, in callback
    my_plants=get_plants(access_token)
  File "/hassio_bticino_smarter/bticino.py", line 307, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'
192.168.1.212 - - [25/Nov/2022 18:36:23] "GET /callback?code=eyJraWQ...... HTTP/1.1" 500 -
```

**Comment by andrea-mattioli** [comment]
Quale modello di termostato state provando ad aggiungere?
Quello è il tipico errore della versione con il firmware netatmo lo smarther2

**Comment by fuzzybear62** [comment]
Ciao Andrea,

io ho tutti smarther 1, ma l'errore è andato via senza fare nulla dopo 
un giorno. Possibile failure delle API legrand?

Grazie

a

Il 26/11/22 19:15, Andrea Mattioli ha scritto:

**Comment by almico** [comment]
Io ho un BTicino SX8000 Smarther.

**Comment by almico** [comment]
Ok. Ci sono riuscito.
Qualche nota, nel caso qualche altro utente avesse lo stesso problema mio:

- Il mio acconto, probabilmente, era precedente ad una qualche nuova integrazione con LeGrand.
- Nella app BTicino c'era una sezione per ACCESSO TERZE PARTI che, in maniera che poteva essere più chiara, mi ha portato a creare un nuovo account. Una volta fatto, mi ha detto di aver "collegato" il vecchio al nuovo account. A scanso di equivoci, nella app, ho fatto il logout e sono rientrato direttamente col nuovo account.
- A questo punto ho rimosso l'addon da HA, ed ho cercato di cancellare ogni cartella che potesse contenere dati relativi all'addon stesso su HA.
- Rifatte la subscription e la richiesta di application su LeGrand, ho aspettato che venisse tutto accettato.
- A questo punto, ho reinserito tutta la configurazione nell'addon, ed ho ricevuto lo stesso errore della volta precedente. Il problema era NEL MIO BROWSER, perché, pur avendo cambiato le credenziali di accesso a LeGrand, l'addon non faceva un logout (per evitare questo problema) seguito da un nuovo login (con le nuove credenziali). Ho ovviato a questo problema facendo il GET YOUR CODE in una Incognito Window di Chrome.

Fatto tutto questo, sono riuscito, finalmente, a vedere il mio termostato dentro HA 🥳

**Comment by andrea-mattioli** [comment]
grazie per il feedback
