### ISSUE TITLE
App not working anymore

### ISSUE THREAD

**Issue by rtirelli** [andrea-mattioli/mattiols_hassio_repository#6]
Hi Andrea,

since some days I could not get the app working anymore. Itried already to rebuild the app and when I accept to give the access I get the following error message. What am I doing wrong here? Thanks.

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by andrea-mattioli** [comment]
Hi, bticino/legrand have changed the privacy policy,  try to open the thermostat's bticino official app and accept the new policy.
Then retry to use my add-on.
A.

**Comment by rtirelli** [comment]
Ah ok, it could be that the reason. I though it wasthe firmware update that fixed the problem, but I had to accept the new policy too. Now I understand.. thank you very much. The problem has been solved now
