### ISSUE TITLE
Cannot start the add-on

### ISSUE THREAD

**Issue by polmdm** [andrea-mattioli/mattiols_hassio_repository#63]
Hi, I'm trying to add the Smarther Thermostat Bticino X8000 to my HA integration nevertheless, once configured the add-on, if I try to start it I got the following error in the log:

s6-overlay-suexec: fatal: can only run as pid 1

I'am running Home Assistant 2023.1.2 (Operating System 9.4) and the latest (0.7) release of the add-on. Hope that someone could help me!

**Comment by andrea-mattioli** [comment]
Hi you must use v2 addon with 2.8 versionRegards Inviato da iPhoneIl giorno 10 gen 2023, alle ore 12:23, polmdm ***@***.***> ha scritto:﻿
Hi, I'm trying to add the Smarther Thermostat Bticino X8000 to my HA integration nevertheless, once configured the add-on, if I try to start it I got the following error in the log:
s6-overlay-suexec: fatal: can only run as pid 1
I'am running Home Assistant 2023.1.2 (Operating System 9.4) and the latest (0.7) release of the add-on. Hope that someone could help me!

**Comment by polmdm** [comment]
Sorry, my bad! Fixed
