### ISSUE TITLE
Automazioni Bticino X8000 v2 "Questa automazione non può essere modificata dall'interfaccia utente, perché non è memorizzata nel file automations.yaml o non ha un ID."

### ISSUE THREAD

**Issue by Dirdan** [andrea-mattioli/mattiols_hassio_repository#64]
Ciao a tutti, nella creazione di alcune automazioni, ho notato che quelle create dal plugin Bticino X8000 V2 riportano l'avvertenza:

Questa automazione non può essere modificata dall'interfaccia utente, perché non è memorizzata nel file automations.yaml o non ha un ID.

E' normale che sia così? oppure è richiesto qualche aggiornamento?

Grazie

**Comment by almico** [comment]
Questo problema è diventato piuttosto importante alla luce del messaggio che mi è appena apparso nella mia installazione di HA:

![image](https://user-images.githubusercontent.com/15247405/236387202-b1826e77-fe9f-41e1-8ebd-7d0703858a82.png)

Oltre a non sapere come risolvere quel `choose a value for 'Only accessible from the local network'` (dovrei attivare o disattivare quel checkbox?), prima di farlo, dovrei comunque memorizzare l'automazione.
Come è corretto procedere?
Grazie.

**Comment by andrea-mattioli** [comment]
L'automazione è gestita dal package, quindi non disponibile da interfaccia utente.
Ho rilasciato la versione 2.9, che fixa il package per questa nuova feature aggiunta per i webhook.

**Comment by Roky8-6** [comment]
> L'automazione è gestita dal package, quindi non disponibile da interfaccia utente. Ho rilasciato la versione 2.9, che fixa il package per questa nuova feature aggiunta per i webhook.

Ciao Andrea, io ho aggiornato alla 2.9 ma ho sempre l'errore del webhook :/
Per caso oltre ai soliti passaggi post aggiornamento, per questo  bisogna effettuare qualche altra cosa?

questo è quello che ricevo anche dopo l'aggiornamento:

Aggiorna l'attivazione del webhook: mattiols_x_8000
Questo smette di funzionare nella versione 2023.7.0. Risolvi il problema prima di effettuare l'aggiornamento.
È necessario scegliere se l'attivazione dell'automazione del webhook mattiols_x_8000 è accessibile da Internet. [Modifica l'automazione](https://192.168.1.118:8123/config/automation/edit/mattiols_x8000_webhook) "automation 42", (automation.automation_40) e fai clic sull'icona a forma di ingranaggio accanto all'ID webhook per scegliere un valore per 'Accessibile solo dalla rete locale'

Attenzione - 4/5/2023
Grazie e.....

Grazie mille per quello che fai :)

**Comment by andrea-mattioli** [comment]
Come scritto nelle note del Change log...
![image](https://user-images.githubusercontent.com/5707570/236774501-8a24aaf7-0da0-43c5-964b-ce6fde4f63ef.png)

https://github.com/andrea-mattioli/mattiols_hassio_repository/blob/master/bticino_X8000_v2/README.md#4-home-assistant-integration

**Comment by Roky8-6** [comment]
> Come scritto nelle note del Change log... ![image](https://user-images.githubusercontent.com/5707570/236774501-8a24aaf7-0da0-43c5-964b-ce6fde4f63ef.png)
> 
> https://github.com/andrea-mattioli/mattiols_hassio_repository/blob/master/bticino_X8000_v2/README.md#4-home-assistant-integration

Ciao Andrea,
ti ho scritto proprio perchè ho seguito le note ecc.. purtroppo per me il problema è rimasto :( Per questo ti chiedevo se c'era qualche altra cosa da fare... Proverò con il disinstallare e reinstallare l'addon
