### ISSUE TITLE
COMMAND

### ISSUE THREAD

**Issue by giugit** [andrea-mattioli/mattiols_hassio_repository#8]
Hi Andrea thanks for your job it works Greath!
I tried also the upgrade... The card show correctly the status of the Termostat but the command do not seems to work
Could you suggest a complete working example (Set to automatic or manual)  with

MQTT command payload

Thank YOu!

**Comment by giugit** [comment]
SOLVED i had set use_ssl: 'True but work only with use_ssl: False.
I don't know why... i have the ssl installed on hassio! I opened only the port 5588 on router...
I have to open also the 80 for use use_ssl: 'True?

**Comment by andrea-mattioli** [comment]
Hi, 
you must use_ssl: false if you are using an external reverse proxy, but if you have a direct connection from internet to my app you must use use_ssl: true.
My app on startup discovering all certificates presents on your Home Assistant installation (for example duck DNS), if you don't have an existing certificate will be generated and in this case yes you must open the port 80 to validate the new certificate

**Comment by giugit** [comment]
THank You Andrea I have DUCK DNS installed but if i put use use_ssl: true the commands not work is only possible read value from the Termostat... the command work only with use use_ssl: false! I don't know why!

**Comment by giugit** [comment]
I have to start with use_ssl: true otherwise the sensors are all unkown... but the commands do not work... i have to switch to use_ssl: false to make them work!

**Comment by andrea-mattioli** [comment]
update to last release
